Repository mysociety/alaveteli, pull requests merged in 2018-08, with the labels that each got.

#4751 Bump public_suffix from 1.4.6 to 2.0.5
  Gemfile
  Gemfile.lock
Labels: 6 - awaiting deploy, dependencies

#4666 [pro#523] Allow sending of batches to be resumed
  app/models/info_request_batch.rb
  spec/models/info_request_batch_spec.rb
Labels: 5 - awaiting review

#4747 Bump pg from 0.18.4 to 0.20
  Gemfile
  Gemfile.lock
Labels: 6 - awaiting deploy

#4774 [pro#552] Limit who sees "Get started" help message
  app/views/alaveteli_pro/dashboard/index.html.erb
  app/views/alaveteli_pro/info_requests/index.html.erb
Labels: 6 - awaiting deploy

#4768 [#4749] Don't re-summarise batch requests until all requests have been created
  app/models/info_request_batch.rb
  spec/models/info_request_batch_spec.rb
Labels: 6 - awaiting deploy

#4810 Tweak to styling of logged in menu link and pro pill
  app/assets/stylesheets/responsive/_header_layout.scss
  app/assets/stylesheets/responsive/_header_style.scss
  app/views/general/_log_in_bar.html.erb
Labels: 6 - awaiting deploy

#4809 [pro#545] fix for action menu and sidebar clashing in mobile view
  app/assets/stylesheets/responsive/_global_layout.scss
  app/assets/stylesheets/responsive/_request_layout.scss
Labels: 6 - awaiting deploy

#4816 [#4815] Add missing translation wrapper
  app/views/reports/new.html.erb
Labels: 4 - now
