Repository mysociety/alaveteli, pull requests merged in 2018-04, with the labels that each got.

#4593 [pro#463] Limit rendering of batch authority search results
  app/assets/javascripts/alaveteli_pro/batch_authority_search/results.js
Labels: 6 - awaiting deploy

#4573 Fix pagination on InfoRequestBatchController#show
  app/controllers/info_request_batch_controller.rb
  app/views/info_request_batch/show.html.erb
Labels: 6 - awaiting deploy

#4597 [#4426] Remove double encoding from authority select
  app/assets/javascripts/alaveteli_pro/authority_select.js
Labels: 6 - awaiting deploy

#4596 Update charlock_holmes gem
  Gemfile.lock
Labels: 6 - awaiting deploy

#4595 [#4156] More error handling in temp:populate_missing_attachment_files
  lib/tasks/temp.rake
Labels: 6 - awaiting deploy

#4589 [#4404] Fix for anonymous requests ability check
  app/models/ability.rb
  spec/models/ability_spec.rb
Labels: 6 - awaiting deploy

#4602 Update changelog with password hashing switch
  doc/CHANGES.md
Labels: 6 - awaiting deploy

#4604 Update Dalli
  Gemfile.lock
Labels: 6 - awaiting deploy

#4594 [pro#501] Destroy embargoes with their info request
  app/models/info_request.rb
  doc/CHANGES.md
  spec/models/info_request_spec.rb
Labels: 5 - awaiting review

#4592 Improved handling of failed Xapian indexing
  lib/acts_as_xapian/acts_as_xapian.rb
  spec/lib/acts_as_xapian_spec.rb
Labels: 4 - now

#4607 Collapse top-level groups in Pro batch browse UI
  app/assets/javascripts/alaveteli_pro/batch_authority_search/browse.js
  app/assets/stylesheets/responsive/alaveteli_pro/_batch_request_authority_search_style.scss
  app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
Labels: 6 - awaiting deploy

#4621 [#4549] Sanitize PublicBody#notes in batch builder
  app/helpers/alaveteli_pro/batch_request_authority_searches_helper.rb
  app/views/alaveteli_pro/batch_request_authority_searches/_search_result.html.erb
  app/views/alaveteli_pro/draft_info_request_batches/_summary.html.erb
  spec/helpers/alaveteli_pro/batch_request_authority_searches_helper_spec.rb
Labels: 6 - awaiting deploy
