Repository mysociety/alaveteli, pull requests merged in 2018-07, with the labels that each got.

#4440 Add an admin footer
  app/assets/stylesheets/admin.scss
  app/views/layouts/admin.html.erb
  doc/CHANGES.md
Labels: 0 - backlog

#4715 Update robots.txt
  public/robots.txt
Labels: 3 - current sprint

#4723 [pro#246] Add Pro upsell to user/rate_limited
  app/views/user/rate_limited.html.erb
Labels: 5 - awaiting review

#4736 July 2017 update deployment
  assets/img/informini.jpg
  deployments.md
Labels: 5 - awaiting review

#4730 [pro#268] Highlight menu tabs for batch
  app/views/alaveteli_pro/general/_nav_items.html.erb
Labels: 6 - awaiting deploy

#4716 [pro#173] Check that 'pro' is enabled before showing pro content in the menu bar
  app/views/general/_log_in_bar.html.erb
  app/views/general/_responsive_topnav.html.erb
  spec/views/general/_log_in_bar.html.erb_spec.rb
  spec/views/general/_responsive_topnav.html.erb_spec.rb
Labels: 6 - awaiting deploy

#4731 Bump fast_gettext from 1.1.0 to 1.1.2
  Gemfile.lock
Labels: 6 - awaiting deploy

#4748 [pro#539] Fix losing draft on pagination
  app/assets/javascripts/alaveteli_pro/batch_authority_search/results.js
Labels: 4 - now

#4753 Prevent .hidden_message text content hitting bottom of container
  app/assets/stylesheets/responsive/_request_layout.scss
Labels: 5 - awaiting review

#4750 Remove mentions of chat from alaveteli.org/community
  community/index.md
Labels: 5 - awaiting review
