Repository mysociety/alaveteli, pull requests merged in 2018-05, with the labels that each got.

#4630 [#1278] Fix Regexp for handling no-reply emails
  app/models/incoming_message.rb
  spec/models/incoming_message_spec.rb
Labels: 6 - awaiting deploy

#4629 Info request refactoring
  app/models/info_request.rb
Labels: 3 - current sprint

#4620 [pro#477] Delist unrequestable authorities from Batch
  app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb
  app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb
  app/views/alaveteli_pro/batch_request_authority_searches/_search_results.html.erb
Labels: 4 - now

#4648 Correct links to Twitter profile
  _includes/es/footer.html
  _includes/footer.html
Labels: 6 - awaiting deploy

#4641 [#2942] Add link to main request JSON from details page
  app/views/request/details.html.erb
Labels: 6 - awaiting deploy

#4608 Make it quicker to ban users in admin interface
  app/controllers/admin_users_account_suspensions_controller.rb
  app/views/admin_user/_user_table.html.erb
  app/views/admin_user/show.html.erb
  config/routes.rb
  doc/CHANGES.md
  spec/controllers/admin_users_account_suspensions_controller_spec.rb
Labels: 6 - awaiting deploy

#4655 [#4631] Use `match_array` in tests when comparing arrays
  spec/models/public_body_spec.rb
Labels: 6 - awaiting deploy

#4646 [#4634] Stripe transient spec errors
  spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
Labels: 6 - awaiting deploy

#4652 [pro#362] Remove delay from batch sending for poller users
  app/models/info_request_batch.rb
Labels: 6 - awaiting deploy
