Repository mysociety/alaveteli, pull requests merged in 2018-09, with the labels that each got.

#4824 Bump coveralls from 0.8.5 to 0.8.22
  Gemfile
  Gemfile.lock
Labels: 6 - awaiting deploy, dependencies

#4851 Properly handle next/previous navigation on 2-message threads
  app/assets/javascripts/alaveteli_pro/request_navigation.js
Labels: 6 - awaiting deploy

#4852 Pin i18n < 0.9.3
  Gemfile
  Gemfile.lock
Labels: 6 - awaiting deploy

#4848 Move required upgrade steps to the top of the section
  doc/CHANGES.md
Labels: 6 - awaiting deploy

#4850 Fix spec_helper deprecation warning
  spec/spec_helper.rb
Labels: 6 - awaiting deploy

#4862 Bump newrelic_rpm from 5.3.0.346 to 5.4.0.347
  Gemfile.lock
Labels: 6 - awaiting deploy

#4836 [pro#561] Remove double-height batch margin
  app/assets/stylesheets/responsive/alaveteli_pro/_requests_layout.scss
  app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
Labels: 6 - awaiting deploy

#4835 [pro#497] Distinguish requests vs batches in pro request list
  app/assets/stylesheets/responsive/alaveteli_pro/_requests_style.scss
Labels: 6 - awaiting deploy

#4812 Allow users to switch status with keyboard
  app/assets/stylesheets/responsive/_global_style.scss
  app/views/alaveteli_pro/info_requests/_sidebar.html.erb
Labels: 6 - awaiting deploy

#4868 Update changelog
  doc/CHANGES.md
Labels: 3 - current sprint
