Repository mysociety/alaveteli, pull requests merged in 2019-10, with the labels that each got.

#5359 Download geoip data on install
  script/rails-deploy-before-down
Labels: 5 - awaiting review

#5400 [pro#597] Fix rendering of Stripe errors
  app/controllers/alaveteli_pro/subscriptions_controller.rb
  doc/CHANGES.md
Labels: 5 - awaiting review

#5402 [#5401] Fix multiple internal admin bodies
  app/models/public_body.rb
Labels: 6 - awaiting deploy

#5406 Auto-correct Style/NilComparison
  lib/tasks/config_files.rake
Labels: 6 - awaiting deploy

#5408 Bump rubyzip from 1.2.2 to 1.3.0
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  config/initializers/rubyzip.rb
Labels: 6 - awaiting deploy, dependencies, security

#5375 [#4636] Fix User#updated_at being changed by cron job
  app/mailers/track_mailer.rb
  doc/CHANGES.md
  spec/mailers/track_mailer_spec.rb
Labels: 6 - awaiting deploy

#5428 [#5419] Fix issue with report button styling
  app/assets/stylesheets/responsive/_request_style.scss
  app/views/comment/_single_comment.html.erb
  app/views/request/_incoming_correspondence.html.erb
  app/views/request/_outgoing_correspondence.html.erb
Labels: 6 - awaiting deploy
