Repository mysociety/alaveteli, pull requests merged in 2019-06, with the labels that each got.

#5217 [#4902] Update changelog
  doc/CHANGES.md
Labels: 6 - awaiting deploy

#5236 [#5234] Fix dependency loading
  config/application.rb
Labels: 6 - awaiting deploy

#5232 [#4971] Add Ubuntu 18.04 LTS (Bionic) Support
  Vagrantfile
  config/initializers/backport_pg_10_support_to_rails_4.rb
  config/packages.ubuntu-bionic
  script/site-specific-install.sh
Labels: 6 - awaiting deploy

#5239 Add a banner promoting AlaveteliCon 2019
  _layouts/default.html
  _layouts/es/default.html
  assets/css/alaveteli-org.css
  assets/css/alaveteli-org.css.map
  assets/sass/alaveteli-org.scss
Labels: 5 - awaiting review

#5237 [Rails 5] Bump/add development gems
  Gemfile
  Gemfile.rails5.lock
  config/environments/development.rb
Labels: 6 - awaiting deploy

#5240 Annotate models
  app/models/incoming_message_error.rb
  spec/factories/alaveteli_pro/draft_info_request_batches.rb
  spec/factories/alaveteli_pro/embargo_extensions.rb
  spec/factories/alaveteli_pro/embargos.rb
  spec/factories/alaveteli_pro/request_summaries.rb
  spec/factories/alaveteli_pro/request_summary_categories.rb
Labels: 5 - awaiting review

#5242 [Rails 5] Make sure cache files get the correct read permissions
  app/controllers/application_controller.rb
  spec/controllers/request_controller_spec.rb
Labels: 3 - current sprint

#5244 [#4902] Improve InfoRequest#title format validation
  app/models/info_request.rb
Labels: 6 - awaiting deploy

#5252 Add GitHub sponsorship file
  .github/FUNDING.yml
Labels: 6 - awaiting deploy

#5254 [#5251] Allow `InfoRequest.guess_by_incoming_subject` to handle emails without subject lines
  app/models/info_request.rb
  spec/models/info_request_spec.rb
Labels: 6 - awaiting deploy

#5259 Security gem updates
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: 5 - awaiting review

#5262 Add temp rake task to convert saved params to ActiveModel::Type::Integer
  doc/CHANGES.md
  lib/tasks/temp.rake
Labels: 6 - awaiting deploy
