Repository mysociety/alaveteli, pull requests merged in 2019-11, with the labels that each got.

#5348 [Rails 5.1] Avoid raising errors by calling `sanitize` when construction SQL statements
  app/models/public_body.rb
Labels: 0 - backlog

#5349 [Rails 5.1] Fix track_mailer specs
  spec/mailers/track_mailer_spec.rb
Labels: 0 - backlog

#5350 [Rails 5.1] Remove ActiveSupport.halt_callback_chains_on_return_false override
  config/initializers/new_framework_defaults.rb
Labels: 3 - current sprint

#5451 Bump rails-html-sanitizer from 1.0.4 to 1.3.0
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5453 Bump will_paginate from 3.1.6 to 3.1.8
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5455 Don't use deprecated success? predicate
  spec/controllers/admin_censor_rule_controller_spec.rb
  spec/controllers/admin_comment_controller_spec.rb
  spec/controllers/admin_incoming_message_controller_spec.rb
  spec/controllers/admin_outgoing_message_controller_spec.rb
  spec/controllers/admin_public_body_categories_controller_spec.rb
  spec/controllers/admin_public_body_controller_spec.rb
  spec/controllers/admin_public_body_headings_controller_spec.rb
  spec/controllers/admin_request_controller_spec.rb
  spec/controllers/admin_user_controller_spec.rb
  spec/controllers/alaveteli_pro/stripe_webhooks_controller_spec.rb
  spec/controllers/alaveteli_pro/subscriptions_controller_spec.rb
  spec/controllers/api_controller_spec.rb
  spec/controllers/comment_controller_spec.rb
  spec/controllers/followups_controller_spec.rb
  spec/controllers/general_controller_spec.rb
  spec/controllers/help_controller_spec.rb
  spec/controllers/info_request_batch_controller_spec.rb
  spec/controllers/public_body_controller_spec.rb
  spec/controllers/request_controller_spec.rb
  spec/controllers/track_controller_spec.rb
  spec/controllers/user_controller_spec.rb
  spec/controllers/user_profile/about_me_controller_spec.rb
  spec/views/general/frontpage.html.erb_spec.rb
  spec/views/public_body/list.html.erb_spec.rb
  spec/views/public_body/show.html.erb_spec.rb
Labels: 6 - awaiting deploy

#5450 Upgrade to Rails 5.1
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/models/info_request.rb
  app/models/outgoing_message.rb
  app/models/public_body.rb
  app/models/user.rb
  gems/alaveteli_features/alaveteli_features.gemspec
Labels: 6 - awaiting deploy

#5445 Add binstubs to easily use the Rails next gemfile
  bin/bundle_next
  bin/rails_next
  bin/rspec_next
Labels: 6 - awaiting deploy

#5470 [#5469] Fix load-sample-data script
  script/load-sample-data
Labels: 6 - awaiting deploy
