Repository mysociety/alaveteli, pull requests merged in 2019-05, with the labels that each got.

#5172 Skip rendering large category in batch browse mode
  app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
Labels: 6 - awaiting deploy

#5184 Fix path problem for external commands used by alaveteli
  lib/alaveteli_external_command.rb
Labels: 6 - awaiting deploy

#5185 Set friendly hostname for Vagrant VM
  Vagrantfile
Labels: 6 - awaiting deploy

#5206 [#5201] Remove record tag helpers
  app/views/admin_holidays/index.html.erb
Labels: 6 - awaiting deploy

#5181 Enable Layout/EmptyLines* cops
  .ruby-style.yml
Labels: 3 - current sprint

#5197 Gitignore tweaks
  .gitignore
Labels: 6 - awaiting deploy

#5210 Remove log/.keep
  log/.keep
Labels: 6 - awaiting deploy

#5216 [Rails 5] Don't use log tags in Rails 4
  config/environments/production.rb
Labels: 5 - awaiting review

#5211 [Rails 5] Only eager load Ruby source lib files
  config/application.rb
Labels: 6 - awaiting deploy
