Repository mysociety/alaveteli, pull requests merged in 2020-04, with the labels that each got.

#5601 [#5171] Hide banned users photo
  app/controllers/request_controller.rb
  app/models/user.rb
  app/views/comment/_single_comment.html.erb
  app/views/statistics/_people_leaderboard.html.erb
  app/views/user/_user_listing_single.html.erb
  app/views/user/show/_show_profile.html.erb
  doc/CHANGES.md
  spec/controllers/request_controller_spec.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: 6 - awaiting deploy

#5591 Remove cookie storage in GA
  app/views/application/_ga_code.html.erb
  app/views/layouts/default.html.erb
  app/views/widgets/show.html.erb
  doc/CHANGES.md
Labels: 5 - awaiting review

#5597 Refactor attachments controller
  app/controllers/attachments_controller.rb
  app/models/incoming_message.rb
  spec/controllers/attachments_controller_spec.rb
  spec/integration/incoming_mail_spec.rb
Labels: 6 - awaiting deploy

#5603 Update grantable roles in user admin UI
  app/models/role.rb
  app/views/admin_user/_form.html.erb
  app/views/admin_user/index.html.erb
  spec/models/role_spec.rb
Labels: 6 - awaiting deploy

#5522 Bump routing-filter from 0.6.2 to 0.6.3
  Gemfile.lock
Labels: dependencies

#5521 Bump dalli from 2.7.8 to 2.7.10
  Gemfile.lock
Labels: dependencies

#5611 Fix installer permission issues
  script/install-as-user
  script/site-specific-install.sh
Labels: 6 - awaiting deploy

#5605 Remove parse_unparsed_pro
  lib/tasks/incoming_messages.rake
  script/parse-unparsed-pro
Labels: 6 - awaiting deploy

#5610 Hotfix/0.37.1.0
  config/initializers/alaveteli.rb
  doc/CHANGES.md
  script/site-specific-install.sh
Labels: 6 - awaiting deploy

#5563 Set money gem rounding mode
  config/initializers/money.rb
Labels: 6 - awaiting deploy

#5606 Bump secure_headers to 3.9.0
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: 6 - awaiting deploy, dependencies, security

#5612 Refactor embargo forms
  app/helpers/alaveteli_pro/info_requests_helper.rb
  app/views/alaveteli_pro/info_requests/_embargo_create_form.html.erb
  app/views/alaveteli_pro/info_requests/_embargo_extension_form.html.erb
  spec/fixtures/locale/es/app.po
  spec/helpers/alaveteli_pro/info_requests_helper_spec.rb
Labels: 6 - awaiting deploy

#5593 [fnf#11] Add data models for projects feature
  app/models/project.rb
  app/models/project_membership.rb
  app/models/project_resource.rb
  app/models/role.rb
  app/models/user.rb
  config/initializers/alaveteli_features.rb
  db/migrate/20200311141432_create_projects.rb
  db/migrate/20200311141504_create_project_memberships.rb
  db/migrate/20200314215007_create_project_resources.rb
  db/seeds.rb
  lib/configuration.rb
  spec/factories/project_memberships.rb
  spec/factories/project_resources.rb
  spec/factories/projects.rb
  spec/fixtures/roles.yml
  spec/models/project_membership_spec.rb
  spec/models/project_resource_spec.rb
  spec/models/project_spec.rb
Labels: 6 - awaiting deploy

#5616 Refactor embargo extension form
  app/views/alaveteli_pro/info_requests/_embargo_extension_form.html.erb
  app/views/alaveteli_pro/info_requests/_embargo_form.html.erb
Labels: 6 - awaiting deploy

#5615 Further refactoring of embargo_create_form
  app/helpers/alaveteli_pro/info_requests_helper.rb
  app/views/alaveteli_pro/info_requests/_embargo_create_form.html.erb
  config/initializers/inflections.rb
  spec/helpers/alaveteli_pro/info_requests_helper_spec.rb
Labels: 6 - awaiting deploy

#5627 [#5542] share by link prep 3
  app/controllers/attachments_controller.rb
  app/controllers/concerns/fragment_cachable.rb
  spec/controllers/attachments_controller_spec.rb
  spec/integration/errors_spec.rb
Labels: 6 - awaiting deploy

#5630 Remove duplicate perform_caching config
  config/environments/development.rb
Labels: 6 - awaiting deploy

#5623 Fix alaveteli configuration defaults
  lib/configuration.rb
Labels: 6 - awaiting deploy

#5635 Force Style/SignalException to use only_raise
  .ruby-style.yml
Labels: 6 - awaiting deploy

#5617 [fnf#20] Projects home
  app/controllers/projects/projects_controller.rb
  app/models/ability.rb
  app/models/project.rb
  app/views/projects/projects/show.html.erb
  config/routes.rb
  spec/controllers/projects/projects_controller_spec.rb
  spec/factories/projects.rb
  spec/models/ability_spec.rb
  spec/models/project_spec.rb
Labels: 6 - awaiting deploy

#5629 [fnf#13] Classifications - prep 2
  app/controllers/alaveteli_pro/classifications_controller.rb
  app/controllers/classifications_controller.rb
  app/controllers/concerns/classifiable.rb
  app/views/classifications/message.html.erb
  config/routes.rb
  spec/controllers/alaveteli_pro/classifications_controller_spec.rb
  spec/controllers/classifications_controller_spec.rb
  spec/support/shared_examples_for_adding_classification_message.rb
Labels: 6 - awaiting deploy
