Repository mysociety/alaveteli, pull requests merged in 2020-09, with the labels that each got.

#5885 Bump rails to 5.2.4.4
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5896 Cleanup alaveteli localization
  lib/alaveteli_localization.rb
  lib/alaveteli_localization/hyphenated_locale.rb
  lib/alaveteli_localization/locale.rb
  lib/alaveteli_localization/underscorred_locale.rb
  spec/lib/alaveteli_localization/hyphenated_locale_spec.rb
  spec/lib/alaveteli_localization/locale_spec.rb
  spec/lib/alaveteli_localization/underscorred_locale_spec.rb
  spec/support/alaveteli_localization/spec_helpers.rb
Labels: awaiting-review

#5897 [eu#106] Fix the locale switcher current locale
  app/controllers/application_controller.rb
Labels: awaiting-deploy

#5893 [#5382] Ensure the underscore locale is included in i18n fallbacks
  config/application.rb
  config/initializers/alaveteli.rb
  lib/alaveteli_localization.rb
  lib/alaveteli_localization/hyphenated_locale.rb
  lib/alaveteli_localization/locale.rb
  lib/alaveteli_localization/underscorred_locale.rb
  spec/lib/alaveteli_localization/hyphenated_locale_spec.rb
  spec/lib/alaveteli_localization/locale_spec.rb
  spec/lib/alaveteli_localization/underscorred_locale_spec.rb
  spec/lib/alaveteli_localization_spec.rb
Labels: awaiting-deploy

#5894 Add specs for IncomingMessage#specific_from_name?
  spec/models/incoming_message_spec.rb
Labels: awaiting-deploy

#5898 Minor optimisation in Locale.parse
  lib/alaveteli_localization/locale.rb
  spec/lib/alaveteli_localization/locale_spec.rb
Labels: awaiting-deploy
