Repository mysociety/alaveteli, pull requests merged in 2020-06, with the labels that each got.

#5691 [fnf#28] User-specific classifications queue
  app/controllers/projects/classifies_controller.rb
  app/models/project/queue/base.rb
  app/models/project/queue/classifiable.rb
  app/views/projects/classifies/_sidebar.html.erb
  config/routes.rb
  spec/controllers/projects/classifies_controller_spec.rb
  spec/factories/projects.rb
  spec/models/project/queue/classifiable_spec.rb
  spec/support/project_queue_context.rb
  spec/support/project_queue_examples.rb
Labels: awaiting-deploy

#5693 [fnf#28] extract queue
  app/assets/javascripts/general.js
  app/controllers/projects/extracts_controller.rb
  app/models/project/queue/extractable.rb
  app/views/projects/extracts/_form.html.erb
  config/routes.rb
  spec/controllers/projects/extracts_controller_spec.rb
  spec/models/project/queue/extractable_spec.rb
  spec/support/project_queue_context.rb
Labels: awaiting-review

#5687 Update company details in footer
  _includes/es/footer.html
  _includes/footer.html
Labels: awaiting-review

#5662 [Security] Bump rack from 2.0.8 to 2.2.2
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  lib/strip_empty_sessions.rb
  spec/controllers/projects/base_controller_spec.rb
  spec/lib/strip_empty_sessions_spec.rb
Labels: awaiting-deploy, dependencies, security

#5702 Bump listen from 3.0.8 to 3.1.5
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5568 [Rails 5.2] Resolve dangerous query method deprecations
  app/controllers/request_game_controller.rb
  app/models/info_request.rb
  app/models/public_body.rb
  lib/acts_as_xapian/acts_as_xapian.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#5707 Fix category header association inverse of option
  app/models/public_body_heading.rb
Labels: awaiting-deploy

#5705 Bump will_paginate from 3.1.8 to 3.3.0
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5700 Remove :pro_batch_access feature flag
  app/controllers/alaveteli_pro/batch_request_authority_searches_controller.rb
  app/services/alaveteli_pro/access.rb
  app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
  spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb
  spec/integration/alaveteli_pro/request_creation_spec.rb
  spec/services/alaveteli_pro/access_spec.rb
Labels: awaiting-deploy

#5701 [pro#360] Remove :info_request_batch_zip_download feature flag
  app/views/alaveteli_pro/info_request_batches/_info_request_batch.html.erb
Labels: awaiting-deploy

#5676 Add public_network vagrant setting
  .vagrant.yml.example
  Vagrantfile
Labels: awaiting-review

#5685 [fnf#30] Hide correspondence footers
  app/views/comment/_single_comment.html.erb
  app/views/followups/new.html.erb
  app/views/projects/classifies/show.html.erb
  app/views/projects/extracts/show.html.erb
  app/views/request/_correspondence.html.erb
  app/views/request/_correspondence_footer.html.erb
  app/views/request/_incoming_correspondence.html.erb
  app/views/request/_outgoing_correspondence.html.erb
  app/views/request/events/_comment.html.erb
  app/views/request/events/_followup_resent.html.erb
  app/views/request/events/_followup_sent.html.erb
  app/views/request/events/_resent.html.erb
  app/views/request/events/_response.html.erb
  app/views/request/events/_send_error.html.erb
  app/views/request/events/_sent.html.erb
  app/views/request/show.html.erb
Labels: awaiting-deploy

#5696 [fnf#28] Refactor queues
  app/controllers/projects/classifies_controller.rb
  app/controllers/projects/extracts_controller.rb
  app/models/project/queue.rb
  app/models/project/queue/base.rb
  app/models/project/queue/classifiable.rb
  app/models/project/queue/extractable.rb
  app/models/project/queue/session_backend.rb
  spec/controllers/projects/classifies_controller_spec.rb
  spec/controllers/projects/extracts_controller_spec.rb
  spec/models/project/queue/classifiable_spec.rb
  spec/models/project/queue/extractable_spec.rb
  spec/models/project/queue/session_backend_spec.rb
  spec/models/project/queue_spec.rb
  spec/support/project_queue_context.rb
  spec/support/project_queue_examples.rb
Labels: awaiting-deploy

#5755 Install development dependencies on Travis
  script/rails-deploy-before-down
Labels: awaiting-deploy

#5754 Pin launchy at < 2.5.0
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5753 Bump annotate from 2.7.2 to 3.1.0
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  script/annotate-models
Labels: dependencies

#5757 [#1391] Replace rmagick with mini_magick
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/models/profile_photo.rb
  spec/models/profile_photo_spec.rb
Labels: awaiting-deploy

#5752 Drop NewRelic
  .travis.yml
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  bin/mongrel_rpm
  bin/newrelic
  bin/newrelic_cmd
  bin/nrdebug
  config/deploy.rb
  config/general.yml-example
  config/newrelic.yml-example
  doc/CHANGES.md
Labels: awaiting-deploy

#5750 [fnf#34] Project data download
  app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
  app/controllers/projects/downloads_controller.rb
  app/helpers/download_helper.rb
  app/models/ability.rb
  app/models/project/export.rb
  app/models/project/export/info_request.rb
  app/views/projects/projects/show.html.erb
  config/routes.rb
  spec/controllers/projects/downloads_controller_spec.rb
  spec/models/ability_spec.rb
  spec/models/project/export/info_request_spec.rb
  spec/models/project/export_spec.rb
Labels: awaiting-deploy

#5748 [#5069] Rails 5.2 upgrade
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/models/mail_server_log.rb
  bin/bundle
  bin/setup
  bin/update
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/alaveteli.rb
  config/initializers/application_controller_renderer.rb
  config/initializers/assets.rb
  config/initializers/backport_pg_10_support_to_rails_4.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/initializers/wrap_parameters.rb
  doc/CHANGES.md
  gems/alaveteli_features/alaveteli_features.gemspec
  lib/js_helper_xss_patch.rb
  lib/yaml_compatibility.rb
  spec/controllers/track_controller_spec.rb
Labels: awaiting-deploy

#5768 Drop public_suffix gem
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: awaiting-deploy, dependencies

#5621 [#1431] Fix transient spec failure
  spec/controllers/request_controller_spec.rb
  spec/integration/errors_spec.rb
  spec/integration/localisation_spec.rb
  spec/integration/sign_in_with_redirect_spec.rb
  spec/support/shared_context_for_local_requests.rb
  spec/support/shared_context_for_show_exceptions.rb
Labels: awaiting-deploy

#5770 Bump fast_gettext from 1.1.2 to 2.0.2
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5769 Bump gettext from 2.3.9 to 3.2.9
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: dependencies

#5709 [#5624] Ignore spam address case
  app/models/spam_address.rb
  spec/models/spam_address_spec.rb
  spec/spec_helper.rb
Labels: awaiting-deploy
