Repository mysociety/alaveteli, pull requests merged in 2020-07, with the labels that each got.

#5782 Change deprecated methods
  app/controllers/admin_announcements_controller.rb
  app/controllers/admin_censor_rule_controller.rb
  app/controllers/admin_comment_controller.rb
  app/controllers/admin_holidays_controller.rb
  app/controllers/admin_incoming_message_controller.rb
  app/controllers/admin_outgoing_message_controller.rb
  app/controllers/admin_public_body_categories_controller.rb
  app/controllers/admin_public_body_controller.rb
  app/controllers/admin_public_body_headings_controller.rb
  app/controllers/admin_request_controller.rb
  app/controllers/admin_user_controller.rb
  app/controllers/alaveteli_pro/draft_info_request_batches_controller.rb
  app/controllers/alaveteli_pro/draft_info_requests_controller.rb
  app/controllers/alaveteli_pro/info_requests_controller.rb
  app/models/alaveteli_pro/request_filter.rb
  app/models/alaveteli_pro/request_summary.rb
  app/models/incoming_message.rb
  app/models/info_request.rb
  db/migrate/20170717141302_drop_public_body_translated_columns.rb
  lib/tasks/cleanup.rake
  lib/tasks/temp.rake
  spec/controllers/admin_holidays_controller_spec.rb
  spec/controllers/admin_outgoing_message_controller_spec.rb
  spec/controllers/followups_controller_spec.rb
  spec/controllers/request_controller_spec.rb
  spec/mailers/request_mailer_spec.rb
  spec/models/alaveteli_pro/request_filter_spec.rb
  spec/models/info_request_spec.rb
  spec/models/mail_server_log_spec.rb
  spec/models/outgoing_message_spec.rb
  spec/models/public_body_spec.rb
  spec/models/user_spec.rb
Labels: awaiting-deploy

#5780 Revert "Fix monkeypatched Time/String comparison"
  config/initializers/alaveteli.rb
  lib/fixture_set_table_rows_patch.rb
Labels: awaiting-deploy

#5778 Drop coffee-rails gem
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/assets/javascripts/admin/admin.coffee
  app/assets/javascripts/admin/admin.js
Labels: awaiting-deploy

#5777 Remove compass-rails gem
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/assets/stylesheets/admin.scss
Labels: awaiting-deploy, dependencies

#5814 Update footer.html
  _includes/es/footer.html
  _includes/footer.html
Labels: awaiting-review

#5813 Remove delorean
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  spec/controllers/admin_comment_controller_spec.rb
  spec/controllers/admin_info_request_event_controller_spec.rb
  spec/controllers/admin_outgoing_message_controller_spec.rb
  spec/controllers/alaveteli_pro/embargo_extensions_controller_spec.rb
  spec/controllers/statistics_controller_spec.rb
  spec/factories/alaveteli_pro/embargos.rb
  spec/helpers/alaveteli_pro/info_requests_helper_spec.rb
  spec/helpers/info_request_helper_spec.rb
  spec/integration/classify_request_spec.rb
  spec/lib/alaveteli_pro/metrics_report_spec.rb
  spec/lib/alaveteli_rate_limiter/backends/pstore_database_spec.rb
  spec/lib/alaveteli_rate_limiter/ip_rate_limiter_spec.rb
  spec/lib/alaveteli_rate_limiter/rate_limiter_spec.rb
  spec/lib/alaveteli_rate_limiter/window_spec.rb
  spec/lib/user_stats_spec.rb
  spec/mailers/alaveteli_pro/embargo_mailer_spec.rb
  spec/mailers/request_mailer_spec.rb
  spec/models/alaveteli_pro/embargo_spec.rb
  spec/models/alaveteli_pro/to_do_list/overdue_request_spec.rb
  spec/models/alaveteli_pro/to_do_list/very_overdue_request_spec.rb
  spec/models/info_request/prominence/embargo_expired_today_query_spec.rb
  spec/models/info_request/prominence/public_query_spec.rb
  spec/models/info_request/state/calculator_spec.rb
  spec/models/info_request/state/overdue_query_spec.rb
  spec/models/info_request/state/very_overdue_query_spec.rb
  spec/models/info_request_event_spec.rb
  spec/models/info_request_spec.rb
  spec/models/notification_spec.rb
  spec/models/project/export_spec.rb
  spec/models/statistics_spec.rb
  spec/models/user/transaction_calculator_spec.rb
  spec/models/user_spec.rb
  spec/services/info_request_batch_metrics_spec.rb
  spec/services/info_request_batch_zip_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples_for_phase_counts.rb
  spec/views/followups/_followup.html.erb_spec.rb
  spec/views/notification_mailer/info_request_batches/messages/_embargo_expiring.text.erb_spec.rb
Labels: awaiting-deploy, dependencies

#5766 Bump rubocop from 0.63.1 to 0.81.0
  .hound.yml
  .ruby-style.yml
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/controllers/concerns/classifiable.rb
  lib/configuration.rb
Labels: awaiting-deploy

#5818 Remove whitespace in translated EN strings.
  locale/en/app.po
Labels: awaiting-deploy

#5474 [#3546] Fix issue applying censor rule to binary data
  app/models/censor_rule.rb
  lib/alaveteli_text_masker.rb
  spec/lib/alaveteli_text_masker_spec.rb
  spec/models/censor_rule_spec.rb
Labels: awaiting-deploy

#5820 Use GitHub actions to run RuboCop linter
  .github/workflows/rubocop.yml
  .hound.yml
Labels: awaiting-deploy

#5829 Fix geoip download rake task
  lib/tasks/geoip.rake
Labels: awaiting-deploy

#5817 [Rails 6] Initial dev
  app/controllers/admin_public_body_controller.rb
  app/controllers/api_controller.rb
  app/controllers/attachments_controller.rb
  app/controllers/track_controller.rb
  app/helpers/application_helper.rb
  app/models/dataset/value.rb
  app/models/public_body.rb
  app/views/admin_public_body_change_requests/add_accepted.text.erb
  app/views/admin_public_body_change_requests/update_accepted.text.erb
  config/initializers/new_framework_defaults.rb
  lib/user_stats.rb
  spec/controllers/admin_raw_email_controller_spec.rb
  spec/controllers/alaveteli_pro/batch_downloads_controller_spec.rb
  spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb
  spec/controllers/api_controller_spec.rb
  spec/controllers/attachments_controller_spec.rb
  spec/controllers/projects/downloads_controller_spec.rb
  spec/controllers/request_controller_spec.rb
  spec/controllers/services_controller_spec.rb
  spec/controllers/track_controller_spec.rb
  spec/integration/errors_spec.rb
  spec/integration/search_request_spec.rb
Labels: awaiting-deploy, has-blockers
