Repository mysociety/alaveteli, pull requests merged in 2020-05, with the labels that each got.

#5642 [fnf#13] Project classifications
  app/controllers/alaveteli_pro/classifications_controller.rb
  app/controllers/concerns/classifiable.rb
  app/controllers/projects/base_controller.rb
  app/controllers/projects/classifications_controller.rb
  app/controllers/projects/extracts_controller.rb
  app/models/ability.rb
  app/models/project.rb
  config/routes.rb
  spec/controllers/classifications_controller_spec.rb
  spec/controllers/projects/base_controller_spec.rb
  spec/controllers/projects/classifications_controller_spec.rb
  spec/models/ability_spec.rb
  spec/models/project_spec.rb
  spec/support/shared_examples_for_adding_classification_message.rb
Labels: 6 - awaiting deploy

#5647 Add download links to batch sidebar
  app/models/info_request_batch.rb
  app/views/info_request_batch/_downloads.html.erb
  app/views/info_request_batch/show.html.erb
  spec/models/info_request_batch_spec.rb
Labels: 6 - awaiting deploy

#5650 [fnf#60] Refactor ActionController#authenticated?
  app/controllers/application_controller.rb
Labels: 6 - awaiting deploy

#5654 [fnf#20] Extraction data models
  .codeclimate.yml
  app/models/dataset.rb
  app/models/dataset/key.rb
  app/models/dataset/key_set.rb
  app/models/dataset/value.rb
  app/models/dataset/value_set.rb
  app/models/project.rb
  app/views/projects/dataset/key_sets/_key_set.html.erb
  app/views/projects/dataset/keys/_base_key.html.erb
  app/views/projects/dataset/keys/_boolean_key.html.erb
  app/views/projects/dataset/keys/_key.html.erb
  app/views/projects/dataset/keys/_numeric_key.html.erb
  app/views/projects/dataset/keys/_text_key.html.erb
  app/views/projects/extracts/_sidebar.html.erb
  app/views/projects/extracts/show.html.erb
  db/migrate/20200501183039_create_dataset_key_sets.rb
  db/migrate/20200501183049_create_dataset_keys.rb
  db/migrate/20200501183102_create_dataset_value_sets.rb
  db/migrate/20200501183111_create_dataset_values.rb
  spec/factories/dataset_key_sets.rb
  spec/factories/dataset_keys.rb
  spec/factories/dataset_value_sets.rb
  spec/factories/dataset_values.rb
  spec/factories/projects.rb
  spec/models/dataset/key_set_spec.rb
  spec/models/dataset/key_spec.rb
  spec/models/dataset/value_set_spec.rb
  spec/models/dataset/value_spec.rb
  spec/models/project_spec.rb
Labels: awaiting-deploy

#5653 [fnf#23] Classification show controller stub
  app/controllers/projects/classifies_controller.rb
  app/views/projects/classifies/show.html.erb
  config/routes.rb
  spec/controllers/projects/classifications_controller_spec.rb
  spec/controllers/projects/classifies_controller_spec.rb
Labels: awaiting-deploy

#5660 [fnf#28] Add Project#classifiable_requests
  app/models/project.rb
  spec/models/project_spec.rb
Labels: awaiting-review

#5667 [fnf#20] Fix project extract form fields/labels
  app/views/projects/dataset/keys/_key.html.erb
Labels: awaiting-deploy

#5659 [fnf#20] Projects extract design
  app/assets/stylesheets/responsive/_global_style.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_extract_style.scss
  app/assets/stylesheets/responsive/all.scss
  app/views/projects/dataset/keys/_base_key.html.erb
  app/views/projects/dataset/keys/_boolean_key.html.erb
  app/views/projects/extracts/_form.html.erb
  app/views/projects/extracts/_sidebar.html.erb
  app/views/projects/extracts/show.html.erb
Labels: awaiting-deploy

#5668 [fnf#23] Add classify form design
  app/assets/stylesheets/responsive/_global_style.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_classify_layout.scss
  app/views/projects/classifies/_sidebar.html.erb
  app/views/request/_state_transition.html.erb
Labels: awaiting-review

#5670 [fnf#23] Add classify task to project homepage
  app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
  app/views/projects/projects/show.html.erb
Labels: awaiting-review

#5657 [fnf#60] Project invites
  app/controllers/projects/invites_controller.rb
  config/routes.rb
  db/migrate/20200515141039_add_invite_token_to_projects.rb
  spec/controllers/projects/invites_controller_spec.rb
  spec/factories/projects.rb
Labels: awaiting-deploy

#5648 [fnf#60] Allow contributors to leave a project
  app/controllers/projects/contributors_controller.rb
  app/controllers/projects/projects_controller.rb
  app/models/ability.rb
  app/models/project.rb
  app/views/projects/projects/show.html.erb
  config/routes.rb
  spec/controllers/projects/contributors_controller_spec.rb
  spec/models/ability_spec.rb
  spec/models/project_spec.rb
Labels: awaiting-deploy

#5671 [fnf] Add a JS refresh button
  app/assets/javascripts/general.js
  app/assets/stylesheets/responsive/_global_style.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
  app/views/projects/classifies/_sidebar.html.erb
  app/views/projects/extracts/_form.html.erb
Labels: awaiting-review

#5675 [fnf#23] Fix submission of classification message via Projects
  app/controllers/projects/classifications_controller.rb
  app/views/classifications/message.html.erb
  spec/controllers/projects/classifications_controller_spec.rb
Labels: awaiting-deploy

#5666 Extract js_correspondence_navigation helper
  app/helpers/info_request_helper.rb
  app/views/alaveteli_pro/info_requests/_sidebar.html.erb
  app/views/projects/classifies/_sidebar.html.erb
  app/views/projects/extracts/_sidebar.html.erb
  spec/helpers/info_request_helper_spec.rb
Labels: awaiting-deploy

#5669 [fnf#23] Classify workflow
  app/controllers/projects/classifications_controller.rb
  app/controllers/projects/classifies_controller.rb
  spec/controllers/projects/classifications_controller_spec.rb
  spec/controllers/projects/classifies_controller_spec.rb
Labels: awaiting-deploy

#5656 [fnf#20] Project submissions
  app/controllers/classifications_controller.rb
  app/controllers/concerns/classifiable.rb
  app/controllers/projects/classifications_controller.rb
  app/controllers/projects/extracts_controller.rb
  app/models/project.rb
  app/models/project/submission.rb
  app/views/projects/extracts/_form.html.erb
  app/views/projects/extracts/_sidebar.html.erb
  app/views/projects/extracts/show.html.erb
  config/routes.rb
  db/migrate/20200509082917_create_project_submissions.rb
  spec/controllers/alaveteli_pro/classifications_controller_spec.rb
  spec/controllers/projects/classifications_controller_spec.rb
  spec/controllers/projects/extracts_controller_spec.rb
  spec/factories/info_request_events.rb
  spec/factories/project_submissions.rb
  spec/models/project/submission_spec.rb
Labels: awaiting-deploy

#5680 [fnf#20] Minor tweaks
  app/assets/stylesheets/responsive/alaveteli_pro/_extract_layout.scss
  app/views/projects/dataset/keys/_base_key.html.erb
Labels: awaiting-deploy

#5682 [fnf#30] Remove the project nav from the project homepage
  app/views/projects/projects/show.html.erb
Labels: awaiting-deploy

#5683 [fnf#30] Hide action menu
  app/views/projects/classifies/show.html.erb
  app/views/projects/extracts/show.html.erb
  app/views/request/_request_header.html.erb
  app/views/request/show.html.erb
Labels: awaiting-deploy

#5684 [fnf] Allow project members to view embargoed requests
  app/models/ability.rb
  spec/models/ability_spec.rb
Labels: awaiting-deploy

#5567 [Rails 5.2] Update specs to use be_successful expectation
  spec/controllers/alaveteli_pro/pages_controller_spec.rb
  spec/controllers/alaveteli_pro/plans_controller_spec.rb
  spec/controllers/general_controller_spec.rb
Labels: awaiting-deploy

#5566 [Rails 5.2] Update expected Cache-Control headers
  spec/controllers/track_controller_spec.rb
Labels: awaiting-deploy

#5565 [Rails 5.2] Update renamed private method call
  app/models/mail_server_log.rb
Labels: awaiting-deploy

#5689 [fnf] Viewing project attachments
  app/controllers/attachments_controller.rb
  app/helpers/info_request_helper.rb
  app/models/user.rb
  spec/controllers/attachments_controller_spec.rb
  spec/helpers/info_request_helper_spec.rb
Labels: awaiting-review
