Repository mysociety/alaveteli, pull requests merged in 2021-07, with the labels that each got.

#6324 Clarify refusal message origin
  app/views/request/_incoming_refusals.html.erb
Labels: awaiting-review

#6227 Document change to erb template files
  docs/installing/cron_and_daemons.md
Labels: awaiting-deploy

#6349 Remove commented Bing Crawl-delay
  public/robots.txt
Labels: awaiting-deploy

#6340 Drop support for Amazon AMI
  docs/developers/index.md
  docs/getting_started.md
  docs/installing/ami.md
  docs/installing/index.md
  docs/installing/manual_install.md
Labels: awaiting-deploy

#6374 Add missing space to translated string
  app/views/user/banned.html.erb
Labels: awaiting-deploy

#6058 [#5440] Add Ruby 2.7 support
  .github/workflows/ci.yml
  lib/quiet_opener.rb
  spec/lib/quiet_open_spec.rb
Labels: awaiting-deploy

#6382 Bump gettext to v3.3.x
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: awaiting-deploy, dependencies

#6383 Fix Kernel deprecated for Ruby 2.7
  app/controllers/application_controller.rb
  app/controllers/general_controller.rb
  app/controllers/request_controller.rb
  app/controllers/services_controller.rb
  lib/tasks/geoip.rake
Labels: awaiting-deploy

#6356 Unfold the details tag if they've come to the page with a hash link
  app/assets/javascripts/wizard.js
  app/assets/stylesheets/responsive/_wizard_style.scss
Labels: awaiting-deploy

#6399 [#1384] Only symlink repository different from destination
  script/install-as-user
Labels: awaiting-deploy

#6397 Hide unnecessary output
  script/site-specific-install.sh
Labels: awaiting-deploy
