Repository mysociety/alaveteli, pull requests merged in 2021-11, with the labels that each got.

#6614 Use human-friendly URLs to body listings
  app/views/public_body/_alphabet.html.erb
  app/views/public_body/list.html.erb
Labels: awaiting-deploy

#6053 Remove dependency on Python
  bin/config
  config/packages
  config/packages.generic
  config/packages.ubuntu-bionic
  config/packages.ubuntu-focal
  config/packages_development
  docker/Dockerfile
  script/load-mail-server-logs
  script/mailin
  script/rails-deploy-before-down
Labels: awaiting-deploy

#6633 [#6566] Fix JSON statistics
  app/controllers/statistics_controller.rb
  spec/controllers/statistics_controller_spec.rb
Labels: awaiting-deploy

#6640 [#6639] Fix the load-mail-server-logs script
  script/load-mail-server-logs
  spec/script/load_mail_server_logs_spec.rb
Labels: awaiting-deploy

#6601 Force SSL
  Gemfile
  Gemfile.lock
  Gemfile.rails_next.lock
  app/models/outgoing_message.rb
  config/application.rb
  config/environments/production.rb
  config/initializers/alaveteli.rb
  lib/attachment_to_html/adapters/google_docs_viewer.rb
  spec/lib/attachment_to_html/adapters/google_docs_viewer_spec.rb
Labels: x:croatia

#6643 Tweak `User#update_login_token`
  app/models/user/login_token.rb
Labels: awaiting-deploy

#6635 [pro#614] Draft menu icon
  app/assets/images/alaveteli-pro/pro-phase-icons--action-needed.png
  app/assets/images/alaveteli-pro/pro-phase-icons--action-needed@2.png
  app/assets/images/alaveteli-pro/pro-phase-icons--complete.png
  app/assets/images/alaveteli-pro/pro-phase-icons--complete@2.png
  app/assets/images/alaveteli-pro/pro-phase-icons--in-progress.png
  app/assets/images/alaveteli-pro/pro-phase-icons--in-progress@2.png
  app/assets/images/alaveteli-pro/pro-phase-icons.png
  app/assets/images/alaveteli-pro/pro-phase-icons@2.png
  app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_layout.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_dashboard_style.scss
  app/views/alaveteli_pro/dashboard/_projects.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#6615 [#6294] Add Debian Bullseye support
  Vagrantfile
  bin/vagrant-bullseye
  doc/CHANGES.md
Labels: awaiting-deploy

#6618 Fix PATH setting for crontab
  config/crontab-example
  doc/CHANGES.md
Labels: awaiting-deploy

#6644 Refactor User#reindex_referencing_models
  app/models/user.rb
Labels: awaiting-deploy

#6660 [#6659] Add deprecation warning for HTML_TO_PDF_COMMAND
  doc/CHANGES.md
  lib/configuration.rb
Labels: awaiting-review

#6208 Add support for Glass Xapian database format
  doc/CHANGES.md
  lib/acts_as_xapian/acts_as_xapian.rb
Labels: awaiting-deploy

#6675 Drop old rubies and operating systems
  .github/workflows/ci.yml
  .ruby-style.yml
  .ruby-version.example
  .vagrant.yml.example
  README.md
  Vagrantfile
  bin/vagrant-bionic
  bin/vagrant-buster
  bin/vagrant-stretch
  config/packages.ubuntu-bionic
  doc/CHANGES.md
  docker/Dockerfile
  lib/tasks/config_files.rake
  script/site-specific-install.sh
Labels: awaiting-deploy

#6690 Remove unused variable
  app/models/incoming_message.rb
Labels: merged-without-review

#6685 Extract pricing_tiers partial
  app/views/alaveteli_pro/plans/_pricing_tiers.html.erb
  app/views/alaveteli_pro/plans/index.html.erb
Labels: merged-without-review

#6692 Adding videos from TICTeC RTK day
  docs/running/resources_for_owners.md
Labels: awaiting-review

#6680 [#6489] Add support for wkhtmltopdf v0.12
  app/controllers/request_controller.rb
  config/initializers/alaveteli.rb
  lib/alaveteli_external_command.rb
  lib/html_to_pdf_converter.rb
  spec/integration/download_request_spec.rb
  spec/lib/alaveteli_external_command_spec.rb
  spec/lib/html_to_pdf_converter_spec.rb
Labels: awaiting-deploy
