Repository mysociety/alaveteli, pull requests merged in 2021-05, with the labels that each got.

#6140 [#6026][JRCT] Automatically check identified refusals
  app/assets/javascripts/wizard.js
  app/helpers/refusal_advice_helper.rb
  app/helpers/refusal_advice_question_form.rb
  app/models/info_request.rb
  app/views/help/_refusal_advice.html.erb
  spec/helpers/refusal_advice_helper_spec.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#6216 Convert templates from Ugly to ERB
  config/alert-tracks-debian.example
  config/crontab-example
  config/poll-for-incoming-debian.example
  config/run-with-rbenv-path.example
  config/send-notifications-debian.example
  config/sysvinit-passenger.example
  config/sysvinit-thin.example
  lib/tasks/config_files.rake
Labels: awaiting-deploy

#6226 Bump Rails to 5.2.6
  Gemfile.lock
  Gemfile.rails_next.lock
Labels: awaiting-deploy

#6199 [#5976] Warn users when a request is authority_only
  app/assets/stylesheets/responsive/_request_style.scss
  app/views/request/_request_subtitle.html.erb
  app/views/request/request_subtitle/allow_new_responses_from/_anybody.html.erb
  app/views/request/request_subtitle/allow_new_responses_from/_authority_only.html.erb
  app/views/request/request_subtitle/allow_new_responses_from/_nobody.html.erb
  spec/views/request/show.html.erb_spec.rb
Labels: awaiting-review

#6240 Remove hard coded feed page
  app/controllers/track_controller.rb
Labels: awaiting-deploy

#6247 [#6246] Handle unconfigured legislation questions
  app/models/refusal_advice.rb
  app/models/refusal_advice/store.rb
  spec/models/refusal_advice/store_spec.rb
  spec/models/refusal_advice_spec.rb
Labels: awaiting-deploy

#6209 Fix snippets error when there are no suggestions
  app/models/refusal_advice.rb
  spec/models/refusal_advice_spec.rb
Labels: awaiting-deploy

#6261 Remove Admin URL from requires admin notifications
  app/mailers/request_mailer.rb
  app/views/request_mailer/requires_admin.text.erb
  spec/mailers/request_mailer_spec.rb
Labels: merged-without-review
