Repository mysociety/alaveteli, pull requests merged in 2021-06, with the labels that each got.

#6280 Use number_field for numeric Dataset::Key
  app/views/projects/dataset/keys/_numeric_key.html.erb
Labels: merged-without-review

#6228 [#5404] Undef Kernel.open before creating open scope
  app/models/public_body_change_request.rb
Labels: awaiting-deploy

#6317 Add new resources for owners page, include in nav menus
  _layouts/page.html
  docs/index.md
  docs/running/resources_for_owners.md
Labels: awaiting-review

#5969 [#5967] Prevent CensorRules being saved when Regexp is bad
  app/models/censor_rule.rb
  config/initializers/alaveteli.rb
  doc/CHANGES.md
  lib/core_ext/warning.rb
  spec/lib/core_ext/warning_spec.rb
  spec/models/censor_rule_spec.rb
Labels: awaiting-deploy

#6248 [#4915] Clearer prominence in request lists
  app/assets/stylesheets/admin.scss
  app/helpers/admin/prominence_helper.rb
  app/helpers/admin_helper.rb
  app/views/admin_request/_some_requests.html.erb
  spec/helpers/admin/prominence_helper_spec.rb
  spec/helpers/admin_helper_spec.rb
Labels: awaiting-deploy

#6252 [#1732] Truncate same name user list
  app/views/user/show.html.erb
  app/views/user/show/_show_same_name_users.html.erb
  config/routes.rb
  doc/CHANGES.md
Labels: awaiting-deploy

#6277 [#3873] Handle UserController#signup ParameterMissing
  app/controllers/user_controller.rb
  spec/controllers/user_controller_spec.rb
Labels: awaiting-deploy

#6278 [#4857] Handle Users::SessionsController#signin ParameterMissing
  app/controllers/users/sessions_controller.rb
  spec/controllers/users/sessions_controller_spec.rb
Labels: awaiting-deploy

#6300 Add a back link to request internal review
  app/views/followups/_form_title.html.erb
Labels: awaiting-deploy

#6306 Hide wizard content from non js users
  app/assets/stylesheets/responsive/_wizard_layout.scss
Labels: awaiting-deploy

#6316 Add pagination translations
  app/helpers/pagination_helper.rb
  doc/CHANGES.md
  spec/fixtures/locale/es/app.po
  spec/helpers/pagination_helper_spec.rb
Labels: awaiting-deploy

#6230 [#6217] Draft request validation
  app/models/alaveteli_pro/draft_info_request_batch.rb
  app/models/concerns/info_request/draft_title_validation.rb
  app/models/concerns/info_request/title_validation.rb
  app/models/draft_info_request.rb
  app/models/info_request.rb
  app/models/info_request_batch.rb
  spec/models/alaveteli_pro/draft_info_request_batch_spec.rb
  spec/models/concerns/info_request/draft_title_validation.rb
  spec/models/concerns/info_request/title_validation.rb
  spec/models/draft_info_request_spec.rb
  spec/models/info_request_batch_spec.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#6323 Add pagination page_gap translation
  app/helpers/pagination_helper.rb
  spec/helpers/pagination_helper_spec.rb
Labels: awaiting-deploy
