Repository mysociety/alaveteli, pull requests merged in 2021-08, with the labels that each got.

#6373 Add local bin directory to test ENV utility path
  config/test.yml
  lib/attachment_to_html/adapter.rb
  lib/attachment_to_html/adapters/pdf.rb
  lib/attachment_to_html/adapters/rtf.rb
  spec/lib/attachment_to_html/adapters/pdf_spec.rb
  spec/lib/attachment_to_html/adapters/rtf_spec.rb
Labels: awaiting-deploy

#6357 [#5649] Fix internal email forwarding
  lib/mail_handler/reply_handler.rb
  script/handle-mail-replies.rb
  spec/lib/mail_handler/reply_handler_spec.rb
Labels: awaiting-deploy

#6337 Extract Statistics::General from GeneralController
  app/controllers/admin_general_controller.rb
  app/controllers/application_controller.rb
  app/controllers/general_controller.rb
  app/models/statistics.rb
  app/models/statistics/general.rb
  spec/controllers/general_controller_spec.rb
  spec/models/statistics/general_spec.rb
Labels: awaiting-deploy

#6411 Fix misleading admin help
  app/views/admin_user/_form.html.erb
Labels: merged-without-review

#6351 Refactor admin dates
  app/helpers/application_helper.rb
  app/views/admin/outgoing_messages/snippets/index.html.erb
  app/views/admin_comment/edit.html.erb
  app/views/admin_comment/index.html.erb
  app/views/admin_general/_change_request_summary.html.erb
  app/views/admin_incoming_message/bulk_destroy.html.erb
  app/views/admin_public_body/_one_list.html.erb
  app/views/admin_request/_some_annotations.html.erb
  app/views/admin_request/_some_requests.html.erb
  app/views/admin_request/show.html.erb
  app/views/admin_track/_some_tracks.html.erb
  app/views/admin_user/_user_table.html.erb
Labels: awaiting-deploy

#6385 [#6322] Fix info request law used
  app/models/info_request.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#6395 [#5960] Refactor and improve Xapian spec setup
  spec/controllers/alaveteli_pro/batch_request_authority_searches_controller_spec.rb
  spec/controllers/general_controller_spec.rb
  spec/controllers/public_body_controller_spec.rb
  spec/controllers/request_controller_spec.rb
  spec/controllers/track_controller_spec.rb
  spec/controllers/user_controller_spec.rb
  spec/integration/alaveteli_pro/admin_spec.rb
  spec/integration/alaveteli_pro/batch_request_spec.rb
  spec/integration/create_request_spec.rb
  spec/integration/search_request_spec.rb
  spec/integration/signin_spec.rb
  spec/integration/track_alerts_spec.rb
  spec/integration/xapian_search_highlighting_spec.rb
  spec/lib/acts_as_xapian_spec.rb
  spec/lib/typeahead_search_spec.rb
  spec/mailers/track_mailer_spec.rb
  spec/models/info_request_spec.rb
  spec/models/xapian_spec.rb
  spec/support/xapian_index.rb
Labels: awaiting-deploy

#6421 Update Xapian configuration loading
  lib/acts_as_xapian/acts_as_xapian.rb
Labels: awaiting-deploy

#6415 [#6414] Fix /version.json
  app/models/statistics/general.rb
  spec/controllers/general_controller_spec.rb
  spec/models/statistics/general_spec.rb
Labels: awaiting-deploy

#6398 Migrate test database for development installs
  script/install-as-user
  script/site-specific-install.sh
Labels: awaiting-deploy

#6410 [#6409] Render newest citations instead of oldest
  .ruby-style.yml
  app/controllers/request_controller.rb
  app/models/citation.rb
  doc/CHANGES.md
  spec/controllers/request_controller_spec.rb
  spec/models/citation_spec.rb
Labels: awaiting-deploy

#6425 [#6423] Show true count of old unclassified requests
  app/controllers/admin_general_controller.rb
  app/views/admin_general/index.html.erb
  spec/controllers/admin_general_controller_spec.rb
Labels: awaiting-deploy

#6430 Update network error spec expectation
  spec/support/shared_examples_for_network_errors_during_send.rb
Labels: awaiting-deploy

#6452 Fire flash style when the URL hashes are clicked after page load
  app/assets/javascripts/wizard.js
Labels: awaiting-deploy

#6451 [#5609] Handle Encoding::ConverterNotFoundError exceptions
  lib/normalize_string.rb
  spec/lib/basic_encoding_spec.rb
Labels: awaiting-deploy

#6453 [#4497] Fix error on Pro info request previews
  app/controllers/alaveteli_pro/info_requests_controller.rb
  spec/controllers/alaveteli_pro/info_requests_controller_spec.rb
Labels: awaiting-deploy

#6454 [#6407] Fix frozen email body
  lib/mail_handler/backends/mail_backend.rb
  spec/fixtures/files/empty-8bit.email
  spec/lib/mail_handler/backends/mail_backend_spec.rb
Labels: awaiting-deploy

#6458 [project#138] Add more videos
  docs/running/resources_for_owners.md
Labels: merged-without-review

#6449 Remove conditionals checking for String#encode
  app/models/censor_rule.rb
  app/models/foi_attachment.rb
  app/models/incoming_message.rb
  app/models/raw_email.rb
  lib/acts_as_xapian/acts_as_xapian.rb
  lib/normalize_string.rb
  spec/lib/acts_as_xapian_spec.rb
  spec/lib/basic_encoding_spec.rb
  spec/lib/mail_handler/backends/mail_backend_spec.rb
  spec/lib/mail_handler/mail_handler_spec.rb
  spec/models/censor_rule_spec.rb
  spec/models/foi_attachment_spec.rb
  spec/models/incoming_message_spec.rb
  spec/models/info_request_event_spec.rb
  spec/models/info_request_spec.rb
  spec/models/post_redirect_spec.rb
  spec/models/raw_email_spec.rb
Labels: awaiting-deploy

#6439 [#4612] Require report reasons
  app/views/classifications/message.html.erb
  app/views/reports/new.html.erb
Labels: awaiting-deploy

#6457 [#6436] Improve test ENV attachment caching
  spec/controllers/attachments_controller_spec.rb
Labels: awaiting-deploy

#6476 [#6046] Fix invalid byte sequence error
  lib/normalize_string.rb
  spec/lib/basic_encoding_spec.rb
Labels: awaiting-deploy

#6481 [#4160] Uncaught duplicate requests
  app/controllers/request_controller.rb
  app/models/info_request.rb
  app/models/info_request_batch.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#5861 Update app config for Rails 6
  bin/setup
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/new_framework_defaults_6_0.rb
Labels: awaiting-deploy, merged-without-review

#6456 [#6361] Add middleware to handle RangeError raised by Rack
  config/application.rb
  lib/deeply_nested_params.rb
  spec/lib/deeply_nested_params_spec.rb
Labels: awaiting-deploy
