Repository mysociety/alaveteli, pull requests merged in 2022-10, with the labels that each got.

#7330 Add a readme for using Docker
  docker/README.md
Labels: merged-without-review

#7333 Fix text rendering of requests
  app/views/request/_hidden_correspondence.text.erb
  app/views/request/_incoming_correspondence.text.erb
  app/views/request/_outgoing_correspondence.text.erb
  app/views/request/show.text.erb
Labels: awaiting-deploy

#7324 [#1005] Preparation work before adding indivdual attachment prominence
  app/helpers/admin/link_helper.rb
  app/helpers/link_to_helper.rb
  app/views/request/_attachments.html.erb
  app/views/request/_bubble.html.erb
  app/views/request/_incoming_correspondence.html.erb
  app/views/request/_outgoing_correspondence.html.erb
Labels: awaiting-deploy

#7334 Refactor rendering of prominence
  app/controllers/outgoing_messages/delivery_statuses_controller.rb
  app/helpers/prominence_helper.rb
  app/models/incoming_message/prominence.rb
  app/models/outgoing_message/prominence.rb
  app/views/request/_attention_requested.html.erb
  app/views/request/_hidden_correspondence.html.erb
  app/views/request/_hidden_request_messages.html.erb
  app/views/request/_incoming_correspondence.html.erb
  app/views/request/_incoming_correspondence.text.erb
  app/views/request/_outgoing_correspondence.html.erb
  app/views/request/_outgoing_correspondence.text.erb
  app/views/request/_prominence.html.erb
  app/views/request/_prominence.text.erb
  app/views/request/_restricted_correspondence.html.erb
  app/views/request/hidden.html.erb
  app/views/request/hidden_correspondence.html.erb
  spec/controllers/outgoing_messages/delivery_statuses_controller_spec.rb
  spec/helpers/prominence_helper_spec.rb
  spec/integration/download_request_spec.rb
  spec/integration/view_request_spec.rb
  spec/views/request/_attention_requested.html.erb_spec.rb
  spec/views/request/_incoming_correspondence.text.erb_spec.rb
Labels: awaiting-deploy

#7359 [#7358] Add incoming_message_dom_id helper
  app/helpers/link_to_helper.rb
  app/views/request/_attachments.html.erb
  spec/helpers/link_to_helper_spec.rb
Labels: merged-without-review

#7318 Minor cleanup of download raw email admin UI
  app/views/admin_raw_email/show.html.erb
Labels: merged-without-review

#7319 Clean up incoming message raw email actions
  app/views/admin_incoming_message/_actions.html.erb
Labels: awaiting-deploy, merged-without-review

#7335 [#6746] Add InfoRequest prominence reason
  app/assets/javascripts/admin/admin.js
  app/assets/stylesheets/admin.scss
  app/controllers/admin_request_controller.rb
  app/controllers/services_controller.rb
  app/helpers/prominence_helper.rb
  app/models/concerns/admin_column.rb
  app/models/info_request.rb
  app/views/admin_request/edit.html.erb
  app/views/admin_request/hidden_user_explanation.text.erb
  app/views/admin_request/show.html.erb
  db/migrate/20220928093559_add_prominence_reason_to_info_request.rb
  spec/factories/info_requests.rb
  spec/fixtures/info_requests.yml
  spec/helpers/prominence_helper_spec.rb
  spec/models/info_request_spec.rb
  spec/views/admin_request/hidden_user_explanation.text.erb_spec.rb
Labels: awaiting-review

#7344 Remove `DeliveryStatus#simple`
  app/models/mail_server_log/delivery_status.rb
  app/views/outgoing_messages/delivery_statuses/show.html.erb
  app/views/request/_outgoing_correspondence.html.erb
  spec/models/mail_server_log/delivery_status_spec.rb
Labels: awaiting-deploy

#7388 Add guest ability helper
  app/controllers/public_tokens_controller.rb
  app/models/ability.rb
  spec/models/ability_spec.rb
Labels: merged-without-review

#7381 [#7372] Don't tag defunct bodies with missing email tag
  app/models/public_body.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#7380 Add Ollie Officer fixture user
  spec/fixtures/users.yml
Labels: awaiting-deploy, merged-without-review

#7379 [#7370] Update Pro classification controller auth
  app/controllers/alaveteli_pro/classifications_controller.rb
  spec/controllers/alaveteli_pro/classifications_controller_spec.rb
Labels: awaiting-deploy

#7394 Refactor prominence abilities
  app/models/ability.rb
  spec/controllers/outgoing_messages/delivery_statuses_controller_spec.rb
  spec/models/ability_spec.rb
Labels: awaiting-deploy
