Repository mysociety/alaveteli, pull requests merged in 2022-09, with the labels that each got.

#7161 Refactor AdminColumn module
  app/models/application_record.rb
  app/models/censor_rule.rb
  app/models/comment.rb
  app/models/concerns/admin_column.rb
  app/models/incoming_message.rb
  app/models/info_request.rb
  app/models/info_request_event.rb
  app/models/outgoing_message.rb
  app/models/outgoing_message/snippet.rb
  app/models/public_body.rb
  app/models/user.rb
  app/views/admin/outgoing_messages/snippets/_snippet.html.erb
  app/views/admin_comment/edit.html.erb
  app/views/admin_public_body/_public_body.html.erb
  app/views/admin_public_body/show.html.erb
  app/views/admin_request/_info_request.html.erb
  app/views/admin_request/_some_annotations.html.erb
  app/views/admin_request/show.html.erb
  app/views/admin_user/_user_table.html.erb
  app/views/admin_user/show.html.erb
  spec/models/comment_spec.rb
Labels: awaiting-deploy

#7243 [#387] Notes by tag
  app/helpers/notes_helper.rb
  app/models/public_body.rb
  spec/helpers/notes_helper_spec.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#7256 [#7225] Update tag controller filtering
  app/controllers/admin/tags_controller.rb
  spec/controllers/admin/tags_controller_spec.rb
Labels: awaiting-deploy

#7239 Use correct mime type for cached CSV attachments
  doc/CHANGES.md
  lib/alaveteli_file_types.rb
Labels: awaiting-deploy

#7233 [#3500] Allow admins to destroy post redirects
  app/controllers/admin/post_redirects_controller.rb
  app/views/admin_user/show.html.erb
  config/routes.rb
  doc/CHANGES.md
  spec/controllers/admin/post_redirects_controller_spec.rb
Labels: awaiting-deploy

#7241 Rationalise message admin links
  app/helpers/admin/link_helper.rb
  app/views/admin_incoming_message/_intro.html.erb
  app/views/admin_outgoing_message/_intro.html.erb
  app/views/admin_outgoing_message/edit.html.erb
  doc/CHANGES.md
  spec/helpers/admin/link_helper_spec.rb
Labels: awaiting-deploy

#7266 [#7265] Fix rendering of notes for Pro authority search
  app/assets/javascripts/alaveteli_pro/authority_select.js
  app/helpers/alaveteli_pro/public_bodies_helper.rb
  app/views/alaveteli_pro/public_bodies/_notes.html.erb
  spec/controllers/alaveteli_pro/public_bodies_controller_spec.rb
  spec/helpers/alaveteli_pro/public_bodies_helper_spec.rb
Labels: awaiting-review

#7278 Fix broken notes migration rake task
  lib/tasks/temp.rake
Labels: merged-without-review

#7275 Wrap timeline event times in time tag
  app/views/admin_general/timeline.html.erb
Labels: merged-without-review

#7274 Improve message redelivery markup and UI
  app/views/admin_incoming_message/_actions.html.erb
Labels: merged-without-review

#7288 [#6902] Use both_links for update change requests
  app/views/admin_general/_change_request_summary.html.erb
Labels: merged-without-review

#7301 [#3983] Update `all-authorities.csv` generation
  app/controllers/public_body_controller.rb
  config/crontab-example
  doc/CHANGES.md
  lib/public_body_csv.rb
  lib/tasks/public_body.rake
  spec/controllers/public_body_controller_spec.rb
  spec/fixtures/all-authorities.csv
  spec/lib/public_body_csv_spec.rb
Labels: merged-without-review
