Repository mysociety/alaveteli, pull requests merged in 2022-06, with the labels that each got.

#7004 [#2905] Remove integration with Gaze
  config/general.yml-example
  config/test.yml
  lib/alaveteli_geoip.rb
  lib/configuration.rb
  spec/lib/alaveteli_geoip_spec.rb
  spec/support/gaze.rb
Labels: awaiting-deploy

#7082 Add user IP and country to spam request notice
  app/controllers/request_controller.rb
  app/controllers/user_controller.rb
Labels: awaiting-deploy

#7088 Remove unused route, action and view
  app/controllers/admin_public_body_controller.rb
  app/views/admin_public_body/missing_scheme.html.erb
  config/routes.rb
Labels: awaiting-deploy

#7054 Remove IncomingMessage.get_all_file_extensions
  app/models/incoming_message.rb
  app/views/general/_advanced_search_tips.html.erb
Labels: merged-without-review

#7053 Add IncomingMessage::CacheAttributesFromRawEmail
  app/models/incoming_message.rb
  app/models/incoming_message/cache_attributes_from_raw_email.rb
Labels: awaiting-deploy

#7103 [#7102] Make it clearer that users are making info requests
  app/views/public_body/show.html.erb
  spec/integration/alaveteli_pro/request_creation_spec.rb
  spec/integration/create_request_spec.rb
  spec/views/public_body/show.html.erb_spec.rb
Labels: awaiting-deploy

#7123 [#6999] Prevent admin users from accessing embargoed content
  app/controllers/admin_incoming_message_controller.rb
  app/controllers/admin_outgoing_message_controller.rb
  app/controllers/admin_raw_email_controller.rb
  app/controllers/admin_request_controller.rb
  spec/controllers/admin_incoming_message_controller_spec.rb
  spec/controllers/admin_outgoing_message_controller_spec.rb
  spec/controllers/admin_raw_email_controller_spec.rb
  spec/controllers/admin_request_controller_spec.rb
Labels: awaiting-review
