Repository mysociety/alaveteli, pull requests merged in 2022-04, with the labels that each got.

#6926 Create admin_user fixture as confirmed
  spec/fixtures/users.yml
Labels: awaiting-deploy

#6798 [#5368] Show body change request notes in admin summary
  app/views/admin_general/_change_request_summary.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#6799 [#5368] Show change request notes on body edit page
  app/views/admin_public_body/edit.html.erb
  app/views/admin_public_body/new.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#6888 Show citations on admin pages
  app/helpers/admin/link_helper.rb
  app/helpers/admin_helper.rb
  app/models/info_request_batch.rb
  app/views/admin/citations/_list.html.erb
  app/views/admin_censor_rule/_form.html.erb
  app/views/admin_comment/edit.html.erb
  app/views/admin_general/_to_do_list.html.erb
  app/views/admin_general/timeline.html.erb
  app/views/admin_incoming_message/_intro.html.erb
  app/views/admin_public_body/missing_scheme.html.erb
  app/views/admin_raw_email/show.html.erb
  app/views/admin_request/_some_annotations.html.erb
  app/views/admin_request/_some_requests.html.erb
  app/views/admin_request/show.html.erb
  app/views/admin_track/_some_tracks.html.erb
  app/views/admin_user/_user_table.html.erb
  app/views/admin_user/show.html.erb
  doc/CHANGES.md
  spec/helpers/admin/link_helper_spec.rb
  spec/helpers/admin_helper_spec.rb
  spec/models/info_request_batch_spec.rb
Labels: awaiting-deploy

#6794 Update structure of our custom lib directories
  config/application.rb
  config/initializers/alaveteli.rb
  lib/attachment_to_html.rb
  lib/health_checks.rb
  lib/mail_handler.rb
  script/handle-mail-replies.rb
  spec/lib/mail_handler/reply_handler_spec.rb
Labels: awaiting-deploy

#6913 [sysadmin#1440] Add health check for Xapian job queue length
  config/initializers/health_checks.rb
  lib/health_checks/checks/limit_check.rb
Labels: awaiting-deploy

#6911 Add git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: awaiting-deploy

#6915 [#6914] Generate login tokens UUID with valid namespace
  app/models/user/login_token.rb
Labels: awaiting-deploy

#6927 [#5574] Drop support for PostgreSQL 9.6
  .github/workflows/ci.yml
  doc/CHANGES.md
  docker/Dockerfile-postgres
Labels: awaiting-deploy

#6938 User admin scopes fixes
  app/views/admin_user/_scopes.html.erb
  app/views/admin_user/index.html.erb
  app/views/admin_user/show.html.erb
  app/views/layouts/admin/users.html.erb
Labels: awaiting-deploy, merged-without-review

#6946 Increased width of email box when changing password
  app/assets/stylesheets/responsive/_password_changes_style.scss
  app/assets/stylesheets/responsive/all.scss
Labels: awaiting-deploy

#6966 Improve Xapian jobs health check
  config/initializers/health_checks.rb
  lib/acts_as_xapian/acts_as_xapian.rb
  lib/health_checks/checks/days_ago_check.rb
  lib/health_checks/checks/period_check.rb
  spec/lib/health_checks/checks/period_check_spec.rb
Labels: awaiting-deploy

#6937 Add User#close
  app/models/user.rb
  spec/models/user_spec.rb
Labels: merged-without-review

#6988 [project#145] Add Romania to deployments
  _data/deployments.yml
  assets/img/iastatullaintrebari.jpg
Labels: merged-without-review

#6991 [gh-pages] Expand git.io URLs
  docs/pro/index.md
  docs/pro/pricing.md
Labels: merged-without-review

#6944 Update query order/reorder syntax
  app/controllers/admin_comment_controller.rb
  app/controllers/admin_public_body_controller.rb
  app/controllers/admin_request_controller.rb
  app/controllers/admin_track_controller.rb
  app/controllers/api_controller.rb
  app/controllers/request_controller.rb
  app/controllers/user_controller.rb
  app/mailers/request_mailer.rb
  app/models/alaveteli_pro/draft_info_request_batch.rb
  app/models/alaveteli_pro/request_filter.rb
  app/models/incoming_message.rb
  app/models/info_request.rb
  app/models/info_request_batch.rb
  app/models/outgoing_message.rb
  app/models/public_body.rb
  app/models/public_body_change_request.rb
  app/models/public_body_heading.rb
  app/models/request_classification.rb
  app/models/statistics/leaderboard.rb
  app/models/user.rb
  app/models/user/transaction_calculator.rb
  app/models/user/with_activity_query.rb
  db/migrate/042_unique_user_urls.rb
  lib/acts_as_xapian/acts_as_xapian.rb
  lib/has_tag_string/has_tag_string.rb
  lib/tasks/cleanup.rake
  lib/tasks/export.rake
  lib/tasks/stats.rake
  lib/tasks/users.rake
  spec/controllers/classifications_controller_spec.rb
  spec/controllers/request_controller_spec.rb
  spec/models/info_request_spec.rb
  spec/spec_helper.rb
Labels: awaiting-deploy

#6953 Added styling for "Publish now" button
  app/views/alaveteli_pro/info_requests/_embargo_form.html.erb
Labels: awaiting-deploy

#6703 [#6341] Prepare for Rails 7 upgrade
  Gemfile
  Gemfile.rails_next.lock
  app/views/admin_public_body/show.html.erb
  config/application.rb
  config/initializers/alaveteli.rb
  config/initializers/inflections.rb
  gems/alaveteli_features/alaveteli_features.gemspec
  lib/mail_handler/backends/mail_backend.rb
  lib/patches/action_controller/metal/strong_parameters.rb
  lib/patches/active_support/configuration_file.rb
  spec/factories/mail_server_log_dones.rb
  spec/lib/yaml_compatability_spec.rb
Labels: awaiting-deploy

#6945 Added UI fix to radio elements when making a request
  app/assets/stylesheets/responsive/_new_request_layout.scss
Labels: awaiting-deploy
