Repository mysociety/alaveteli, pull requests merged in 2023-09, with the labels that each got.

#7841 Use muted style for admin comment created date
  app/views/admin_request/_some_annotations.html.erb
Labels: awaiting-review, merged-without-review

#7840 Show the last sent time on outgoing messages
  app/views/admin_request/show.html.erb
Labels: awaiting-review, merged-without-review

#7867 Add admin toolbox section to public body list
  app/assets/stylesheets/admin.scss
  app/views/admin_public_body/_one_list.html.erb
Labels: awaiting-review, merged-without-review

#7868 Improve notes on user name change form
  app/views/users/names/edit.html.erb
Labels: awaiting-review, merged-without-review

#7893 Add ability to ask external caches to invalidate.
  app/jobs/notify_cache_job.rb
  app/models/censor_rule.rb
  app/models/comment.rb
  app/models/foi_attachment.rb
  app/models/info_request.rb
  app/models/info_request_event.rb
  app/models/public_body.rb
  app/models/user.rb
  config/general.yml-example
  lib/configuration.rb
  spec/controllers/admin/foi_attachments_controller_spec.rb
  spec/controllers/admin_incoming_message_controller_spec.rb
  spec/factories/info_request_events.rb
  spec/jobs/notify_cache_job_spec.rb
  spec/models/censor_rule_spec.rb
  spec/models/comment_spec.rb
  spec/models/foi_attachment_spec.rb
  spec/models/info_request_event_spec.rb
  spec/models/info_request_spec.rb
  spec/models/public_body_spec.rb
  spec/models/user_spec.rb
Labels: awaiting-deploy

#7900 [#7877] Fix uuencoding attachment processing
  app/models/incoming_message.rb
  lib/mail_handler/backends/mail_backend.rb
  spec/lib/mail_handler/backends/mail_backend_spec.rb
  spec/lib/mail_handler/mail_handler_spec.rb
Labels: awaiting-deploy

#7901 Add colon after request summary intro
  app/views/notification_mailer/daily_summary.text.erb
  spec/fixtures/files/notification_mailer/daily-summary.txt
  spec/views/notification_mailer/daily_summary.text.erb_spec.rb
Labels: awaiting-deploy

#7899 Enable pry binding via Docker
  docker-compose.yml
Labels: awaiting-deploy

#7921 Fix incoming message rendering
  app/views/request/_attachments.html.erb
Labels: awaiting-deploy, merged-after-staging-test

#7922 Add Xapian Sidekiq queue
  Gemfile
  Gemfile.lock
  app/jobs/info_request_expire_job.rb
  config/sidekiq.yml-example
Labels: awaiting-deploy, merged-after-staging-test

#7923 Remove inline background jobs
  app/jobs/application_job.rb
  config/general.yml-example
  config/test.yml
  lib/configuration.rb
  lib/tasks/config_files.rake
Labels: awaiting-deploy, merged-after-staging-test

#7926 Fix IP address spam sign up check
  app/controllers/concerns/user_spam_check.rb
  app/models/user/with_request.rb
  config/initializers/user_spam_scorer.rb
  lib/user_spam_scorer.rb
  spec/lib/user_spam_scorer_spec.rb
  spec/models/user/with_request_spec.rb
Labels: awaiting-deploy, merged-after-staging-test

#7898 Fix incoming redelivery to multiple
  app/controllers/admin_incoming_message_controller.rb
  spec/controllers/admin_incoming_message_controller_spec.rb
Labels: awaiting-deploy
