Repository mysociety/alaveteli, pull requests merged in 2023-12, with the labels that each got.

#8025 [#7811] Allow InfoRequest to be categorised
  app/controllers/admin/categories_controller.rb
  app/models/category.rb
  app/models/concerns/categorisable.rb
  app/models/info_request.rb
  app/models/public_body.rb
  app/views/admin/categories/_scope.html.erb
  app/views/admin/categories/edit.html.erb
  app/views/admin/categories/index.html.erb
  app/views/admin/categories/new.html.erb
  app/views/admin_general/_admin_navbar.html.erb
  app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
  app/views/public_body/list.html.erb
  doc/CHANGES.md
  lib/tasks/temp.rake
  spec/controllers/admin/categories_controller_spec.rb
  spec/models/category_spec.rb
  spec/models/concerns/categorisable.rb
  spec/models/info_request_spec.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#8041 [#8040] Fix missing attachments exceptions
  app/controllers/attachments_controller.rb
  app/models/foi_attachment.rb
  doc/CHANGES.md
  spec/controllers/attachments_controller_spec.rb
  spec/models/foi_attachment_spec.rb
Labels: merged-without-review

#8045 Add Excel spreadsheet analyzer
  Gemfile
  Gemfile.lock
  doc/CHANGES.md
  gems/excel_analyzer/.gitignore
  gems/excel_analyzer/Gemfile
  gems/excel_analyzer/README.md
  gems/excel_analyzer/Rakefile
  gems/excel_analyzer/bin/console
  gems/excel_analyzer/bin/setup
  gems/excel_analyzer/excel_analyzer.gemspec
  gems/excel_analyzer/lib/excel_analyzer.rb
  gems/excel_analyzer/lib/excel_analyzer/analyzer.rb
  gems/excel_analyzer/lib/excel_analyzer/railtie.rb
  gems/excel_analyzer/spec/excel_analyzer/analyzer_spec.rb
  gems/excel_analyzer/spec/fixtures/data.xlsx
  gems/excel_analyzer/spec/fixtures/plain.txt
  gems/excel_analyzer/spec/fixtures/suspect.xlsx
  gems/excel_analyzer/spec/spec_helper.rb
Labels: awaiting-deploy, merged-without-review

#8050 Add link to admin attachments
  app/views/request/_attachments.html.erb
  doc/CHANGES.md
Labels: merged-without-review

#8055 Fix redirect when category is destroyed
  app/views/admin/categories/edit.html.erb
Labels: merged-without-review
