Repository mysociety/alaveteli, pull requests merged in 2023-03, with the labels that each got.

#7457 [#7456] Allow ex-pro users to followup to private requests
  app/controllers/followups_controller.rb
  doc/CHANGES.md
  spec/controllers/followups_controller_spec.rb
Labels: awaiting-deploy

#7617 Show user messages count in admin UI
  app/models/user.rb
  app/models/user_message.rb
  db/migrate/20230301110831_add_user_messages_count_to_users.rb
  spec/factories/users.rb
  spec/fixtures/users.yml
  spec/models/user_spec.rb
Labels: merged-without-review

#7602 Add comment creation interval rate limit
  app/controllers/comment_controller.rb
  app/models/comment.rb
  app/models/user.rb
  app/views/comment/rate_limited.html.erb
  doc/CHANGES.md
  spec/controllers/comment_controller_spec.rb
  spec/models/comment_spec.rb
  spec/models/user_spec.rb
Labels: awaiting-deploy

#7575 [#1240] Add background job processing
  .ruby-style.yml
  Gemfile
  Gemfile.lock
  app/jobs/application_job.rb
  app/jobs/info_request_expire_job.rb
  app/models/censor_rule.rb
  app/models/public_body.rb
  app/models/user.rb
  bin/sidekiq
  bin/sidekiqmon
  config/application.rb
  config/environments/test.rb
  config/general.yml-example
  config/initializers/sidekiq.rb
  config/packages
  config/packages.generic
  config/packages.ubuntu-focal
  config/rails_env.rb-example
  config/routes.rb
  config/sidekiq.service.example
  config/sidekiq.yml
  config/test.yml
  docker-compose.yml
  lib/configuration.rb
  lib/tasks/config_files.rake
  spec/integration/admin_censor_rule_spec.rb
  spec/jobs/info_request_expire_job_spec.rb
  spec/models/censor_rule_spec.rb
  spec/models/public_body_spec.rb
  spec/models/user_spec.rb
  spec/models/xapian_spec.rb
Labels: awaiting-review

#7634 [#7631] Fix Project request extractable scope
  app/models/project/info_request_extension.rb
  spec/models/project_spec.rb
Labels: merged-without-review

#7641 Project leaderboards
  app/controllers/projects/leaderboards_controller.rb
  app/controllers/projects/projects_controller.rb
  app/models/project/leaderboard.rb
  app/views/projects/projects/show.html.erb
  config/routes.rb
  spec/controllers/projects/leaderboards_controller_spec.rb
  spec/models/project/leaderboard_spec.rb
Labels: awaiting-deploy

#7630 Add daily limit to user message creation
  app/models/user.rb
  app/views/users/messages/rate_limited.html.erb
  doc/CHANGES.md
  spec/models/user_spec.rb
Labels: merged-without-review

#7521 Add list of batch requests to admin user page
  app/controllers/admin_user_controller.rb
  app/models/info_request_batch.rb
  app/views/admin/info_request_batches/_info_request_batch.html.erb
  app/views/admin/info_request_batches/_list.html.erb
  app/views/admin_user/show.html.erb
  doc/CHANGES.md
  spec/models/info_request_batch_spec.rb
  spec/views/admin_user/show.html.erb_spec.rb
Labels: merged-without-review

#7490 Add ability to paginate through batch requests
  app/models/info_request.rb
  app/models/info_request/batch_pagination.rb
  app/views/alaveteli_pro/info_requests/_batch.html.erb
  app/views/info_request_batch/_pagination.html.erb
  app/views/request/_batch.html.erb
  doc/CHANGES.md
  spec/models/info_request/batch_pagination.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#7632 [#6589] Blog refactor
  app/controllers/general_controller.rb
  app/models/blog.rb
  app/views/alaveteli_pro/general/_nav_items.html.erb
  app/views/general/_nav_items.html.erb
  app/views/general/blog.html.erb
  spec/controllers/general_controller_spec.rb
  spec/models/blog_spec.rb
  spec/views/general/blog.html.erb_spec.rb
Labels: awaiting-deploy

#7642 [#6589] Adds blog post model
  app/models/blog.rb
  app/models/blog/post.rb
  app/views/general/blog.html.erb
  db/migrate/20230314171033_create_blog_posts.rb
  spec/factories/blog/posts.rb
  spec/models/blog/post_spec.rb
  spec/models/blog_spec.rb
  spec/views/general/blog.html.erb_spec.rb
Labels: awaiting-deploy

#7621 Add MailHog Docker container
  config/environments/development.rb
  docker-compose.yml
  docker/Dockerfile
  docker/entrypoint.sh
Labels: awaiting-review
