Repository mysociety/alaveteli, pull requests merged in 2023-02, with the labels that each got.

#7524 Allow docker/compose to specify which Ruby version will be used
  docker-compose.yml
  docker/Dockerfile
  docker/env
  docker/reset
  docker/server
  docker/setup
Labels: merged-without-review

#7566 Remove deprecated methods
  app/models/comment.rb
  app/models/incoming_message.rb
Labels: merged-without-review

#7576 Remove PublicBody::Version#notes column
  app/models/public_body.rb
  db/migrate/20230209094128_remove_public_body_version_notes.rb
  spec/factories/public_bodies.rb
  spec/fixtures/public_bodies.yml
  spec/fixtures/public_body_versions.yml
  spec/models/public_body_spec.rb
Labels: merged-without-review

#7577 Add rubocop flags to display useful information
  .github/workflows/rubocop.yml
Labels: merged-without-review

#7541 Rubocop refactor formatstring
  app/mailers/outgoing_mailer.rb
  app/models/foi_attachment.rb
  app/models/mail_server_log/delivery_status.rb
  app/models/mail_server_log/exim_line.rb
  app/models/mail_server_log/postfix_line.rb
  lib/acts_as_xapian/acts_as_xapian.rb
  spec/controllers/attachments_controller_spec.rb
  spec/models/mail_server_log/delivery_status_spec.rb
  spec/models/mail_server_log/exim_line_spec.rb
  spec/models/mail_server_log/postfix_line_spec.rb
  spec/support/email_helpers.rb
Labels: awaiting-deploy

#7563 Extract old request magic variables
  app/models/info_request.rb
  spec/models/info_request_spec.rb
Labels: merged-without-review

#7436 Add InfoRequestEvent#event_type scopes
  app/models/info_request_event.rb
  spec/models/info_request_event_spec.rb
Labels: awaiting-review

#7603 Record user messages
  app/controllers/users/messages_controller.rb
  app/models/user.rb
  app/models/user_message.rb
  db/migrate/20230222154014_create_user_messages.rb
  spec/controllers/users/messages_controller_spec.rb
  spec/factories/user_messages.rb
  spec/models/user_message_spec.rb
Labels: merged-without-review

#7604 Increase comment both_links truncate length
  app/helpers/admin/link_helper.rb
Labels: merged-without-review

#7605 [#1971] Add basic user message opt out
  app/controllers/users/messages_controller.rb
  app/models/user.rb
  app/views/users/messages/opted_out.html.erb
  db/migrate/20230223145243_add_receive_user_messages_to_user.rb
  spec/controllers/users/messages_controller_spec.rb
  spec/factories/users.rb
  spec/fixtures/users.yml
  spec/models/user_spec.rb
Labels: merged-without-review

#7600 [#6154] Make it clearer usernames are published
  app/assets/stylesheets/responsive/_new_request_layout.scss
  app/assets/stylesheets/responsive/_new_request_style.scss
  app/assets/stylesheets/responsive/_request_style.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_new_request_layout.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_new_request_style.scss
  app/views/alaveteli_pro/info_request_batches/_message_preview.html.erb
  app/views/alaveteli_pro/info_requests/_message_preview.html.erb
  app/views/alaveteli_pro/info_requests/_select_authority_form.html.erb
  app/views/alaveteli_pro/info_requests/new.html.erb
  app/views/request/new.html.erb
  app/views/request/preview.html.erb
  doc/CHANGES.md
Labels: merged-without-review
