Repository mysociety/alaveteli, pull requests merged in 2023-11, with the labels that each got.

#7967 Add MailerHelper#case_reference
  app/helpers/mailer_helper.rb
  spec/helpers/mailer_helper_spec.rb
Labels: awaiting-deploy

#7974 Show holding pen guess scores
  app/views/admin_raw_email/_holding_pen.html.erb
Labels: awaiting-deploy

#7983 Update GitHub workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
  .github/workflows/rubocop.yml
Labels: awaiting-review, merged-without-review

#7892 [#7189] Details page showing keys metadata
  app/controllers/request_controller.rb
  app/views/request/details.html.erb
  spec/controllers/request_controller_spec.rb
  spec/views/request/details.html.erb_spec.rb
Labels: awaiting-deploy

#7999 [#1106] Admin view of unmasked incoming message
  app/assets/stylesheets/admin.scss
  app/views/admin/foi_attachments/edit.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#8000 [#1782] Help us CTA from delivery error message
  app/helpers/info_request_helper.rb
  doc/CHANGES.md
  spec/helpers/info_request_helper_spec.rb
Labels: awaiting-deploy

#8002 [#1513, #6871] Signpost request contributions
  app/assets/stylesheets/responsive/_search_style.scss
  app/views/general/_help_requests.html.erb
  app/views/general/_search_latest.html.erb
  app/views/request/list.html.erb
  config/routes.rb
  doc/CHANGES.md
Labels: awaiting-deploy

#8003 [#7971] Update attachment processing
  app/jobs/foi_attachment_mask_job.rb
  app/models/foi_attachment.rb
  app/models/incoming_message.rb
  spec/models/foi_attachment_spec.rb
  spec/models/incoming_message_spec.rb
Labels: awaiting-deploy, merged-without-review

#7363 [#7361] Automatically tag bodies with few public requests
  app/models/info_request.rb
  app/models/public_body.rb
  app/views/admin_public_body/_form.html.erb
  doc/CHANGES.md
  spec/controllers/admin_public_body_controller_spec.rb
  spec/lib/public_body_csv_spec.rb
  spec/models/info_request_spec.rb
  spec/models/public_body_spec.rb
  spec/support/not_many_requests_helper.rb
  spec/support/shared_context_for_not_many_requests_tag.rb
Labels: awaiting-deploy

#7378 [#3830] Update request base calculated status
  app/models/info_request.rb
  app/models/info_request/state/calculator.rb
  app/models/info_request/state/transitions.rb
  doc/CHANGES.md
  spec/models/info_request/state/calculator_spec.rb
  spec/models/info_request_spec.rb
Labels: awaiting-deploy

#8005 Add admin links to and from batch request show action
  app/views/admin/info_request_batches/_admin_columns.html.erb
  app/views/info_request_batch/show.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#8016 Clarify inputs (arguments) to the list_user_domains routine
  lib/user_stats.rb
Labels: awaiting-deploy

#8023 [#7811] Generalised category system
  app/controllers/admin/categories_controller.rb
  app/controllers/admin_public_body_categories_controller.rb
  app/controllers/admin_public_body_headings_controller.rb
  app/helpers/admin_public_body_category_helper.rb
  app/models/category.rb
  app/models/category_relationship.rb
  app/views/admin/categories/_form.html.erb
  app/views/admin/categories/_locale_fields.html.erb
  app/views/admin/categories/edit.html.erb
  app/views/admin/categories/index.html.erb
  app/views/admin/categories/new.html.erb
  app/views/admin_public_body_categories/_category_list_item.html.erb
  app/views/admin_public_body_categories/_form.html.erb
  app/views/admin_public_body_categories/_heading_list.html.erb
  app/views/admin_public_body_categories/_locale_fields.html.erb
  app/views/admin_public_body_categories/edit.html.erb
  app/views/admin_public_body_categories/index.html.erb
  app/views/admin_public_body_categories/new.html.erb
  app/views/admin_public_body_headings/_form.html.erb
  app/views/admin_public_body_headings/_locale_fields.html.erb
  app/views/admin_public_body_headings/edit.html.erb
  app/views/admin_public_body_headings/new.html.erb
  app/views/alaveteli_pro/batch_request_authority_searches/_browse.html.erb
  app/views/public_body/list.html.erb
  config/routes.rb
  db/migrate/20231110122337_create_categories.rb
  db/migrate/20231127110827_create_category_relationships.rb
  doc/CHANGES.md
  lib/tasks/temp.rake
  spec/controllers/admin/categories_controller_spec.rb
  spec/controllers/admin_public_body_categories_controller_spec.rb
  spec/controllers/admin_public_body_headings_controller_spec.rb
  spec/factories/categories.rb
  spec/factories/category_relationships.rb
  spec/fixtures/categories.yml
  spec/fixtures/category_relationships.yml
  spec/fixtures/category_translations.yml
  spec/integration/admin_public_body_category_edit_spec.rb
  spec/integration/admin_public_body_category_new_spec.rb
  spec/integration/admin_public_body_heading_edit_spec.rb
  spec/models/category_relationship_spec.rb
  spec/models/category_spec.rb
  spec/spec_helper.rb
Labels: awaiting-deploy
