Repository mysociety/alaveteli, pull requests merged in 2023-10, with the labels that each got.

#7927 [#7906] Improve description of user danger zone
  app/views/admin_user/edit.html.erb
Labels: awaiting-deploy

#7932 [#7875] Fix attachment processing
  app/controllers/attachment_masks_controller.rb
  app/jobs/foi_attachment_mask_job.rb
  app/models/foi_attachment.rb
  app/models/incoming_message.rb
  spec/controllers/attachment_masks_controller_spec.rb
  spec/jobs/foi_attachment_mask_job_spec.rb
  spec/models/foi_attachment_spec.rb
Labels: awaiting-deploy, tested-on-staging

#7935 [#7934] Fix processing of unsaved attachments
  app/models/foi_attachment.rb
  spec/models/foi_attachment_spec.rb
Labels: tested-on-staging

#7951 [EU#124] Fix loading custom states in theme
  config/initializers/theme_loader.rb
Labels: backport

#7945 [#6606] Add subscription started webhook state
  app/models/webhook.rb
  spec/fixtures/stripe_webhooks/subscription-started.json
  spec/models/webhook_spec.rb
Labels: awaiting-deploy, merged-without-review

#7949 [#7948] Add PublicBody#disclosure_log to JSON
  app/models/public_body.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy, merged-without-review

#7938 [#7027] Add CSV to GoogleDocsViewer
  lib/attachment_to_html/adapters/google_docs_viewer.rb
Labels: awaiting-review

#7836 [#6434] Exclude email providers from body home pages
  app/models/public_body.rb
  app/models/public_body/calculated_home_page.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#7947 [#1264] Update PublicBody#disclosure_log to be translatable
  app/controllers/admin_public_body_controller.rb
  app/models/public_body.rb
  app/views/admin_public_body/_form.html.erb
  app/views/admin_public_body/_locale_fields.html.erb
  lib/tasks/temp.rake
Labels: awaiting-review

#7965 [#7823] Update Docker scripts
  docker/bootstrap
  docker/reset
  docker/setup
Labels: merged-without-review

#7680 [#5371] Update admin timeline event filtering
  app/controllers/admin_general_controller.rb
  app/helpers/admin_general_timeline_helper.rb
  app/views/admin_general/timeline.html.erb
  spec/controllers/admin_general_controller_spec.rb
Labels: awaiting-deploy

#7913 [#7879] Handle multiple addresses in headers
  app/mailers/request_mailer.rb
  app/models/info_request.rb
  spec/mailers/request_mailer_spec.rb
  spec/models/info_request_spec.rb
  spec/support/email_helpers.rb
Labels: awaiting-deploy

#7975 Update AttachmentMaskController referer handling
  app/controllers/attachment_masks_controller.rb
  app/controllers/attachments_controller.rb
  app/views/attachment_masks/done.html.erb
  spec/controllers/attachment_masks_controller_spec.rb
  spec/controllers/attachments_controller_spec.rb
Labels: awaiting-deploy, tested-on-staging

#7171 [#4808] Add the internal ID number to the CSV download
  doc/CHANGES.md
  lib/public_body_csv.rb
  spec/lib/public_body_csv_spec.rb
Labels: awaiting-deploy

#7979 [#7977] Update `AttachmentController#show_as_html` to do attachment masking in the background
  app/controllers/attachment_masks_controller.rb
  app/controllers/attachments_controller.rb
  spec/controllers/attachment_masks_controller_spec.rb
  spec/controllers/attachments_controller_spec.rb
  spec/integration/incoming_mail_spec.rb
Labels: awaiting-deploy
