Repository mysociety/alaveteli, pull requests merged in 2024-04, with the labels that each got.

#8195 [#8190] Fix logout issues
  app/controllers/application_controller.rb
  app/controllers/attachments_controller.rb
Labels: tested-on-staging

#8109 Treat unstemmed words as normal search terms.
  doc/CHANGES.md
  lib/acts_as_xapian/acts_as_xapian.rb
  spec/lib/acts_as_xapian_spec.rb
Labels: awaiting-review

#8126 Citations improvements
  app/helpers/admin/citations_helper.rb
  app/helpers/admin_helper.rb
  app/models/citation.rb
  app/views/admin/citations/_list.html.erb
  app/views/citations/new.html.erb
  db/migrate/20240209162933_change_citation_type_values.rb
  doc/CHANGES.md
  spec/controllers/citations_controller_spec.rb
  spec/helpers/admin/citations_helper_spec.rb
  spec/models/citation_spec.rb
Labels: awaiting-deploy

#8155 Extract User::SpreadableAlerts
  app/models/user.rb
  app/models/user/spreadable_alerts.rb
  spec/models/user/spreadable_alerts.rb
  spec/models/user_spec.rb
Labels: awaiting-deploy

#8158 Strengthen 2FA warning
  app/views/one_time_passwords/show.html.erb
  doc/CHANGES.md
Labels: awaiting-deploy

#8177 [#8176] Update admin list of authority tags
  app/views/admin_public_body/_tag_help.html.erb
  app/views/admin_public_body/import_csv.html.erb
Labels: awaiting-deploy

#8153 [#7771 & #7809] Add styling and rich text notes
  app/assets/javascripts/admin.js
  app/assets/javascripts/admin/notes.js
  app/assets/stylesheets/actiontext.css
  app/assets/stylesheets/admin.scss
  app/assets/stylesheets/responsive/_notes_layout.scss
  app/assets/stylesheets/responsive/_notes_styles.scss
  app/controllers/admin/notes_controller.rb
  app/helpers/notes_helper.rb
  app/models/note.rb
  app/models/public_body.rb
  app/views/active_storage/blobs/_blob.html.erb
  app/views/admin/notes/_form.html.erb
  app/views/admin/notes/_locale_fields.html.erb
  app/views/admin/notes/_note.html.erb
  app/views/admin/notes/_show.html.erb
  app/views/layouts/action_text/contents/_content.html.erb
  app/views/layouts/admin.html.erb
  config/application.rb
  db/migrate/20240227080436_add_style_to_notes.rb
  db/migrate/20240228122324_create_action_text_tables.action_text.rb
  doc/CHANGES.md
  spec/controllers/admin/notes_controller_spec.rb
  spec/factories/notes.rb
  spec/factories/public_bodies.rb
  spec/fixtures/notes.yml
  spec/helpers/notes_helper_spec.rb
  spec/models/note_spec.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#8178 [#7255] Add category notes
  app/controllers/admin/categories_controller.rb
  app/helpers/admin/link_helper.rb
  app/models/category.rb
  app/models/concerns/notable.rb
  app/views/admin/categories/_form.html.erb
  app/views/admin/categories/_locale_fields.html.erb
  doc/CHANGES.md
  spec/controllers/admin/categories_controller_spec.rb
  spec/models/category_spec.rb
Labels: awaiting-deploy, tested-on-staging

#8196 [#8179] Replace public body categories
  app/controllers/public_body_controller.rb
  app/models/public_body.rb
  lib/tasks/export.rake
  spec/controllers/public_body_controller_spec.rb
  spec/models/public_body_spec.rb
Labels: awaiting-deploy

#8197 [#7812] Allow requests to be browsed by tag
  app/controllers/request_controller.rb
  app/views/general/_frontpage_requests_list.html.erb
  app/views/request/_category.html.erb
  app/views/request/_list_results.html.erb
  app/views/request/_request_filter_form.html.erb
  app/views/request/list.html.erb
  config/routes.rb
  doc/CHANGES.md
  lib/xapian_queries.rb
  spec/controllers/request_controller_spec.rb
  spec/controllers/track_controller_spec.rb
  spec/factories/categories.rb
Labels: awaiting-deploy, on-staging

#8201 [#7693] Update InfoRequest#recipient_name_and_email
  app/models/info_request.rb
  doc/CHANGES.md
  spec/models/info_request_spec.rb
Labels: awaiting-deploy, on-staging

#8160 Add default and constraint to CensorRule#regexp
  app/models/censor_rule.rb
  db/migrate/20240313094449_add_not_null_constraint_to_censor_rule_regexp.rb
  doc/CHANGES.md
  spec/factories/censor_rules.rb
  spec/models/censor_rule_spec.rb
Labels: awaiting-deploy

#8205 Switch Authorities and Requests in admin nav
  app/views/admin_general/_admin_navbar.html.erb
Labels: awaiting-deploy
