Repository mysociety/alaveteli, pull requests merged in 2024-10, with the labels that each got.

#8391 Layout and spacing improvements to popup banner
  app/assets/stylesheets/responsive/_popups_layout.scss
Labels: awaiting-deploy

#8399 Fix error handling in script/mailin
  doc/CHANGES.md
  script/mailin
Labels: awaiting-deploy, x:sweden, merged-without-review

#8397 Dataset select
  app/assets/stylesheets/responsive/_global_style.scss
  app/assets/stylesheets/responsive/alaveteli_pro/_projects_layout.scss
  app/controllers/alaveteli_pro/projects_controller.rb
  app/controllers/projects/extracts_controller.rb
  app/javascript/controllers/projects/key_set/select_controller.js
  app/javascript/controllers/projects/key_set_controller.js
  app/models/dataset/key.rb
  app/models/dataset/value.rb
  app/views/alaveteli_pro/projects/_key_set.html.erb
  app/views/alaveteli_pro/projects/_select_key.html.erb
  app/views/alaveteli_pro/projects/edit_key_set.html.erb
  app/views/alaveteli_pro/projects/update_key_set.turbo_stream.erb
  app/views/projects/dataset/keys/_select_key.html.erb
  db/migrate/20240926164308_add_options_to_dataset_key.rb
  doc/CHANGES.md
  spec/factories/dataset_keys.rb
  spec/models/dataset/key_spec.rb
  spec/models/dataset/value_spec.rb
Labels: awaiting-deploy

#8406 Add basic Citation search
  app/controllers/admin/citations_controller.rb
  app/models/citation.rb
  app/views/admin/citations/index.html.erb
  doc/CHANGES.md
  spec/controllers/admin/citations_controller_spec.rb
  spec/models/citation_spec.rb
Labels: awaiting-deploy

#8418 Bump sprockets from `f4d3dae` to `3.7.5`
  Gemfile
  Gemfile.lock
Labels: awaiting-deploy, dependencies, ruby
